"l0c2005qX": {
    rightno   : option1,
    question: "",
    attribute : "",
    op1: "",
    op2: "",
    op3: "",
    op4: "",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},


</****************************************/>


"l0c2005q1": {
    rightno   : option4,
    question: "NH₃CO₂ 3200 Psi চাপে এবং 380°C তাপমাত্রায় সুপারহিটেড অবস্থায় কী হয়?",
    attribute: "",
    op1: "মিথেন গ্যাস উৎপন্ন হবে",
    op2: "অক্সিজেন গ্যাস উৎপন্ন হবে",
    op3: "হাইড্রোজেন সালফাইড উৎপন্ন হবে",
    op4: "অ্যামোনিয়াম কার্বামেট উৎপন্ন হবে",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q2": {
    rightno   : option2,
    question: "NH₃ এবং CO₂ কে 380°C তাপমাত্রায় এবং 3200 Psi চাপে গরম করলে (NH₄)₂CO₃ গঠনের পরে কী হয়?",
    attribute : "",
    op1: "সালফিউরিক অ্যাসিড উৎপন্ন হবে",
    op2: "ইউরিয়া উৎপন্ন হবে",
    op3: "কার্বনিক অ্যাসিড উৎপন্ন হবে",
    op4: "অ্যামোনিয়াম কার্বামেট উৎপন্ন হবে",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q3": {
    rightno   : option1,
    question: "ভালো মানের সিমেন্টের জন্য নিম্নলিখিত কোন অনুপাত অনুসরণ করা উচিত?",
    attribute : "",
    op1: "% CaO / (% SiO₂ + % Fe₂O₃ + % Al₂O₃) = 1.9 - 2.15",
    op2: "% CaO / (% SiO₂ + % Fe₂O₃ + % Al₂O₃) = 2.5 - 4",
    op3: "% Fe₂O₃ / (% CaO + % SiO₂ + % Al₂O₃) = 0.3 - 0.45",
    op4: "% SiO₂ / (% CaO + % Fe₂O₃ + % Al₂O₃) = 0.5 - 0.7",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q4": {
    rightno   : option3,
    question: "ভালো মানের সিমেন্টের জন্য নিম্নলিখিত কোন অনুপাত অনুসরণ করা উচিত?",
    attribute : "",
    op1: "% CaO / % Fe₂O₃ = 2.0 - 3.5",
    op2: "% CaO / % Fe₂O₃ = 2.0 - 3.5",
    op3: "% SiO₂ / % Al₂O₃ = 2.5 - 4",
    op4: "% Fe₂O₃ / % CaO = 0.5 - 1.0",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q5": {
    rightno   : option4,
    question: "IUPAC অনুযায়ী, 1 × 10⁻⁹ m থেকে 1 × 10⁻⁷ m আকারের কণাগুলোকে কী বলা হয়?",
    op1: "পিকো কণা",
    op2: "মিলি কণা",
    op3: "মাইক্রো কণা",
    op4: "ন্যানো কণা",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q6": {
    rightno   : option3,
    question: "নিচের কোনটি অন্তরক পদার্থ?",
    attribute : "",
    op1: "পেট্রোল",
    op2: "জিংক",
    op3: "চিনি",
    op4: "গ্রাফাইট",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q7": {
    rightno   : option4,
    question: "কোন শিল্প বর্জ্যে মারক্যাপটান দূষণকারী থাকে?",
    attribute : "",
    op1: "কাগজ",
    op2: "রং",
    op3: "কীটনাশক",
    op4: "সবগুলো",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q8": {
    rightno   : option4,
    question: "পোর্টল্যান্ড সিমেন্ট উৎপাদনে কোন ধাতু ব্যবহৃত হয়?",
    attribute : "",
    op1: "3CaO.SiO₂",
    op2: "MgO",
    op3: "Fe₂O₃",
    op4: "সবগুলো",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q9": {
    rightno   : option2,
    question: "পাল্প উৎপাদনে ডাইজেস্টারের সাদা তরলে কী থাকে?",
    attribute : "",
    op1: "Na₂SO₄, NaOH, Na₂CO₃",
    op2: "Na₂S, NaOH, Na₂CO₃",
    op3: "NaCl, NaOH, Na₂CO₃",
    op4: "Na₂S, Na₂SO₄, Na₂CO₃",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q10": {
    rightno   : option1,
    question: "কোন ধাতু ত্বকের কোলাজেন প্রোটিনের সাথে বন্ধন তৈরি করে ত্বকের সংযোগ সম্পূর্ণ করে?",
    attribute : "Cr = ক্রোমিয়াম, Pb = সীসা, Sb = অ্যান্টিমনি, As = আর্সেনিক",
    op1: "Cr",
    op2: "Pb",
    op3: "Sb",
    op4: "As",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q11": {
    rightno   : option2,
    question: "ন্যানো পার্টিকেল কোন বিজ্ঞান অনুসরণ করে?",
    attribute : "",
    op1: "শাস্ত্রীয় বলবিদ্যা",
    op2: "কোয়ান্টাম বলবিদ্যা",
    op3: "নিউক্লিয়ার ফিজিক্স",
    op4: "সবগুলো",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q12": {
    rightno   : option3,
    question: "ন্যানো পার্টিকেলের কোন বৈশিষ্ট্য নেই?",
    attribute : "",
    op1: "বাল্ক ম্যাটেরিয়াল",
    op2: "জিরো ডাইমেনশনাল এবং ন্যানো স্ট্রাকচার্ড",
    op3: "নিয়মিত এবং সেমি-ক্রিস্টালাইন ম্যাটেরিয়াল",
    op4: "কোনোটিই নয়",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q13": {
    rightno   : option4,
    question: "ন্যানো পার্টিকেলের বৈশিষ্ট্য –",
    attribute : "",
    op1: "জিরো ডাইমেনশনাল এবং ন্যানো স্ট্রাকচার্ড",
    op2: "বাল্ক ম্যাটেরিয়াল",
    op3: "অ্যামরফাস এবং সেমি-ক্রিস্টালাইন পদার্থ",
    op4: "সবগুলো",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q14": {
    rightno   : option3,
    question: "তামা (Cu) এর কত শতাংশ পুনর্ব্যবহারযোগ্য ধাতু?",
    attribute : "",
    op1: "35%",
    op2: "65%",
    op3: "100%",
    op4: "কোনোটিই নয়",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q15": {
    rightno   : option1,
    question: "অ্যালুমিনিয়াম (Al) এর কত শতাংশ পুনর্ব্যবহারযোগ্য ধাতু নয়?",
    attribute : "",
    op1: "0%",
    op2: "35%",
    op3: "65%",
    op4: "100%",
    proof: "অ্যালুমিনিয়াম (Al) সম্পূর্ণরূপে পুনর্ব্যবহারযোগ্য অর্থাৎ 100% পুনর্ব্যবহারযোগ্য ধাতু।",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q16": {
    rightno   : option1,
    question: "নিচের কোনটি দূষণকারী গ্যাস?",
    attribute : "NOx = নাইট্রোজেন অক্সাইড গোষ্ঠী, He = হিলিয়াম, H₂ = হাইড্রোজেন, Ar = আর্গন",
    op1: "NOx",
    op2: "He",
    op3: "H₂",
    op4: "Ar",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q17": {
    rightno: option4,
    question: "নিচের কোনটি দূষণকারী গ্যাস নয়?",
    attribute : "HCl = হাইড্রোক্লোরিক অ্যাসিড, SO₂ = সালফার ডাইঅক্সাইড, H₂S = হাইড্রোজেন সালফাইড, He = হিলিয়াম",
    op1: "HCl",
    op2: "SO₂",
    op3: "H₂S",
    op4: "He",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q18": {
    rightno: option4,
    question: "নিচের কোনটি দূষণকারী গ্যাস?",
    attribute : "H₂S = হাইড্রোজেন সালফাইড, HF = হাইড্রোজেন ফ্লোরাইড, Ar = আর্গন",
    op1: "H₂S",
    op2: "HF",
    op3: "Ar",
    op4: "A এবং B",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q19": {
    rightno: option2, 
    question: "SO₂ শুদ্ধিকরণে কোন তরল ব্যবহৃত হয়?",
    attribute : "",
    op1: "ফেনল",
    op2: "পানি, NaOH এর মিশ্রণ",
    op3: "ক্লোরিন গ্যাস",
    op4: "হাইড্রোজেন পারঅক্সাইড",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q20": {
    rightno: option1,
    question: "H₂S শুদ্ধিকরণে কোন তরল ব্যবহৃত হয়?",
    attribute : "",
    op1: "NaOH দ্রবণ + ফেনল",
    op2: "ফেনল",
    op3: "পানি, NaOH এর জলীয় দ্রবণ",
    op4: "পানি, HNO₃ এর জলীয় দ্রবণ",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q21": {
    rightno: option2,
    question: "C₄H₉OH + PCl₅ ----> X + Y ? এখানে X এবং Y কী?",
    attribute: "",
    op1: "C₄H₉Cl এবং H₃PO₄",
    op2: "C₄H₉Cl এবং POCl₃",
    op3: "C₄H₉Cl এবং H₂PO₄",
    op4: "C₄H₉Cl এবং H₃PO₃",
    proof: "C₄H₉OH এর সাথে PCl₅ এর বিক্রিয়ায় C₄H₉Cl (X) এবং POCl₃ (Y) গঠিত হয়।",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q22": {
    rightno: option3,
    question: "CH₃COOH + NH₃ ----> X + Y ? এখানে X এবং Y কী?",
    attribute: "",
    op1: "অ্যাসিটামাইড এবং অ্যামোনিয়া",
    op2: "অ্যাসিটোন এবং পানি",
    op3: "অ্যামোনিয়াম অ্যাসিটেট এবং পানি",
    op4: "অ্যাসিটিক অ্যাসিড এবং অ্যামোনিয়া",
    proof: "CH₃COOH এর সাথে NH₃ এর বিক্রিয়ায় অ্যামোনিয়াম অ্যাসিটেট (X) এবং পানি (Y) গঠিত হয়।",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q23": {
    rightno: option4,
    question: "C₆H₅NH₂ + CO₂ ----> X + Y ? এখানে X এবং Y কী?",
    attribute: "",
    op1: "অ্যানিলিন এবং পানি",
    op2: "অ্যামাইন এবং কার্বনিক অ্যাসিড",
    op3: "সায়ানাইড এবং পানি",
    op4: "অ্যামাইড এবং পানি",
    proof: "C₆H₅NH₂ এর সাথে CO₂ এর বিক্রিয়ায় অ্যামাইড (X) এবং পানি (Y) গঠিত হয়।",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q24": {
    rightno: option1,
    question: "CH₃CH₂COOH + NH₃ ----> X + Y ? এখানে X এবং Y কী?",
    attribute: "",
    op1: "ইথাইলামাইন এবং পানি",
    op2: "ইস্টার এবং অ্যামোনিয়া",
    op3: "অ্যামাইড এবং পানি",
    op4: "অ্যালকোহল এবং অ্যামোনিয়া",
    proof: "CH₃CH₂COOH এর সাথে NH₃ এর বিক্রিয়ায় ইথাইলামাইন (X) এবং পানি (Y) গঠিত হয়।",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q25": {
    rightno: option2,
    question: "C₂H₅OH + PCl₃ ----> X + Y ? এখানে X এবং Y কী?",
    attribute: "",
    op1: "C₂H₅Cl এবং H₃PO₃",
    op2: "C₂H₅Cl এবং POCl₃",
    op3: "C₂H₅Cl এবং H₂PO₄",
    op4: "C₂H₅Cl এবং H₃PO₄",
    proof: "C₂H₅OH এর সাথে PCl₃ এর বিক্রিয়ায় C₂H₅Cl (X) এবং POCl₃ (Y) গঠিত হয়।",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q26": {
    rightno: option4,
    question: "C₆H₅OH + SOCl₂ ----> X + Y ? এখানে X এবং Y কী?",
    attribute: "",
    op1: "ফেনল এবং সালফিউরিক অ্যাসিড",
    op2: "ফেনাইল ক্লোরাইড এবং হাইড্রোজেন সালফাইট",
    op3: "সায়ানাইড এবং পানি",
    op4: "ফেনাইল ক্লোরাইড এবং থায়োনাইল ক্লোরাইড",
    proof: "C₆H₅OH এর সাথে SOCl₂ এর বিক্রিয়ায় ফেনাইল ক্লোরাইড (X) এবং থায়োনাইল ক্লোরাইড (Y) গঠিত হয়।",
    pic: "",
    picon: false,
    picproof: "",
},

"l0c2005q27": {
    rightno: option3,
    question: "C₄H₉OH + SOCl₂ ----> X + Y ? এখানে X এবং Y কী?",
    attribute: "",
    op1: "বিউটানল এবং সালফিউরিক অ্যাসিড",
    op2: "বিউটাইল ক্লোরাইড এবং হাইড্রোজেন সালফাইট",
    op3: "বিউটাইল ক্লোরাইড এবং থায়োনাইল ক্লোরাইড",
    op4: "বিউটাইল ক্লোরাইড এবং সালফার ডাইঅক্সাইড",
    proof: "C₄H₉OH এর সাথে SOCl₂ এর বিক্রিয়ায় বিউটাইল ক্লোরাইড (X) এবং থায়োনাইল ক্লোরাইড (Y) গঠিত হয়।",
    pic: "",
    picon: false,
    picproof: "",
},
"l0c2005q36": {},




{
    "l0c2006q01": {
      "question": "Which of the following is the major product when C₂H₅OH reacts with Na?",
      "attribute": "Consider the reactivity of alcohols with metals.",
      "op1": "Ethanol and sodium hydroxide",
      "op2": "Ethoxide ion and hydrogen gas",
      "op3": "Ethane and sodium hydroxide",
      "op4": "Ethene and water",
      "proof": "The reaction between C₂H₅OH (ethanol) and Na (sodium) predominantly produces ethoxide ion and hydrogen gas."
    },
    "l0c2006q02": {
      "question": "What happens when CH₃COOH is treated with PCl₅?",
      "attribute": "Focus on the chlorination of carboxylic acids.",
      "op1": "Formation of acetyl chloride and HCl",
      "op2": "Formation of methyl chloride and carbon dioxide",
      "op3": "Formation of acetic anhydride and phosphorous acid",
      "op4": "Formation of acetone and phosphoric acid",
      "proof": "Treating CH₃COOH (acetic acid) with PCl₅ results in the formation of acetyl chloride and HCl."
    },
    "l0c2006q03": {
      "question": "What is the main product when benzene reacts with CH₃Cl in the presence of AlCl₃?",
      "attribute": "Recall the Friedel-Crafts alkylation of benzene.",
      "op1": "Chlorobenzene",
      "op2": "Benzyl chloride",
      "op3": "Toluene",
      "op4": "Benzaldehyde",
      "proof": "The reaction of benzene with CH₃Cl in the presence of AlCl₃ primarily yields toluene as the product."
    },
    "l0c2006q04": {
      "question": "What is formed when propan-2-ol is oxidized?",
      "attribute": "Consider the oxidation products of secondary alcohols.",
      "op1": "Propanal",
      "op2": "Propanoic acid",
      "op3": "Acetone",
      "op4": "Ethanal",
      "proof": "Oxidation of propan-2-ol typically leads to the formation of acetone."
    }
  }
  
