"l1c2004qX": {
    rightno: option1,
    question: "",
    attribute : "",
    op1: "",
    op2: "",
    op3: "",
    op4: "",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},


<************************************>

"l1c2004q1": {
    rightno: option4,
    question: "To determine the electron charge, e = ?",
    attribute : "e = Electron charge, F = Faraday, N = Avogadro's number",
    op1: "e = F - N",
    op2: "e = F × N",
    op3: "e = N/F",
    op4: "e = F/N",
    proof: "ne × number of ions per gram = nF \n\n Furthermore, Avogadro's number, N is the number of atoms in one gram atom = N \n\n When each electron gained or lost by each one-gram atom transforms into an ion with n charges, then the number of ions produced in one-gram-ion is equal to N \n\n Therefore, ne × N = nF \n\n বা, e = F/N",
    pic: "",
    picon: false,
    picproof: "",
},

"l1c2004q2": {
    rightno: option3,
    question: "Which of the following is Faraday's first law?",
    attribute: "F = Force, W = Amount of substance produced by electricity, Q = Amount of ions, V = Voltage, C = Coulomb, e = Charge of an electron, N = Avogadro's number",
    op1: "F ∝ Q",
    op2: "F ∝ V",
    op3: "W ∝ Q",
    op4: "Q ∝ eN",
    proof: "During electrical analysis, the quantity of any chemical change occurring at any electrode or the quantity of a substance produced at any electrode is directly proportional to the total charge passed through the electrolyte. In other words, W ∝ Q",
    pic: "",
    picon: false,
    picproof: "",
},

"l1c2004q3": {
    rightno: option4,
    question: "According to Faraday's first law, Z = ?",
    attribute: "Z = Proportional constant, F = Force, Q = Amount of ions, V = Voltage, C = Coulomb, W = Amount of substance produced by electricity, e = Charge of an electron, N = Avogadro's number",
    op1: "Z = F/Q",
    op2: "Z = V/Q",
    op3: "Z  = W × Q",
    op4: "Z = W/Q",
    proof: "According to Faraday's first law, W ∝ Q \n\n Or, W = ZQ \n\n or, Z = W/Q",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q4": {
    rightno: option4,
    question: "Capacitance, C = ?",
    attribute: "R = Resistance, K = Coulomb, Q = Amount of ions, V = Voltage, e = Charge of an electron, I = Electric current, t = Time, N = Avogadro's number",
    op1: "C = R / eN",
    op2: "C = I / R",
    op3: "C = R / I",
    op4: "C = 1 / R",
    proof: "The reciprocal of the resistance in an electrical circuit is called its capacitance. In other words, C = 1 / R",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q5": {
    rightno: option1,
    question: "Which one below is correct?",
    attribute: "M = 1 mole of substance, E = Chemical equivalent, Z = Electrochemical equivalent, F = Faraday = 96500 C",
    op1: "E = FZ",
    op2: "E = MZ",
    op3: "E = 1 / M",
    op4: "E = F / Z",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l1c2004q6": {
    rightno: option4,
    question: "Which one below is correct?",
    attribute: "M = 1 mole of substance, E = Chemical equivalent, Z = Electrochemical equivalent, F = Faraday = 96500 C",
    op1: "Z = F / E",
    op2: "Z = EF",
    op3: "Z = 1 / EF",
    op4: "Z = E / F",
    proof:" Z = 1 mole of substance / (molar mass × 96500) \n\n Or, Z = E / 96500 \n\n Or, Z = E / F",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q7": {
    rightno: option1,
    question: "
    The number of electrons passing through a thin aluminum wire when a current of 1.5 amps flows for 30 minutes and 10 seconds can be determined using which of the following formulas?",
    attribute: "I = Current, t = Time of current flow, e = Number of electrons, n = Avogadro's number, F = Faraday = 96500 C",
    op1: "e = Itn / F",
    op2: "e = It / nF",
    op3: "e = It² / nF",
    op4: "e = It / (n+F)",
    proof: "During the time of the current flow, t = (30 × 60 + 10) = 1810 seconds \n\n The total amount of current passed, I = 1.5 × 1810 = 2715 C \n\n Therefore, using the formula, e = nI / F \n\n e = (6.023 × 10²³ × 2715) / 96500 = 1.69 × 10²² electrons. So, the formula is correct",
    pic: "",    
    picon: false,
    picproof: "",
},


"l1c2004q8": {
    rightno: option3,
    question: "The electric potential of a metal, V = ?",
    attribute: "",
    op1: "V = Metal's liquid pressure - Osmotic pressure of the liquid",
    op2: "V = Osmotic pressure of the liquid - Metal's liquid pressure",
    op3: "V = Metal's liquid pressure / Osmotic pressure of the liquid",
    op4: "V = Metal's liquid pressure / Osmotic pressure of the liquid",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q9": {
    rightno: option1,
    question: "If P > P⁰, which of the following is correct?",
    attribute: "P = Liquid pressure, P⁰ = Vapor pressure",
    op1: "The metal plate will acquire a negative charge",
    op2: "A level with negative charge will form around the metal plate",
    op3: "The metal plate will remain unchanged in contact with the liquid",
    op4: "None of the above",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q10": {
    rightno: option3,
    question: "If P < P⁰, which of the following is correct?",
    attribute: "P = Liquid pressure, P⁰ = Vapor pressure",
    op1: "Negatively charged ions in the liquid will be attracted to the surface of the plate",
    op2: "Negatively charged ions in the liquid will be attracted to the surface of the plate",
    op3: "The metal plate will acquire a positive charge",
    op4: "A and B",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l1c2004q11": {
    rightno: option4,
    question: "If P = P⁰, which of the following is correct?",
    attribute: "P = Liquid pressure, P⁰ = Vapor pressure",
    op1: "An electric potential difference will be created",
    op2: "The negatively charged ions in the liquid will be attracted to the surface of the plate",
    op3: "The metal plate will undergo a change in contact with the liquid",
    op4: "The metal plate will remain unchanged in contact with the liquid",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},

"l1c2004q12": {
    rightno: option4,
    question: "Standard cell potential, E⁰𝒸ₑₗₗ = ?",
    attribute: "",
    op1: "E⁰𝒸ₑₗₗ = E⁰ᵣᵢ𝓰ₕₜ₍ᵣₑ𝒹₎ - E⁰ₗₑ𝒻ₜₜ₍ᵣₑ𝒹₎",
    op2: "E⁰𝒸ₑₗₗ = E⁰ₗₑ𝒻ₜₜ₍ᵣₑ𝒹₎ - E⁰ᵣᵢ𝓰ₕₜ₍ᵣₑ𝒹₎",
    op3: "E⁰𝒸ₑₗₗ = E⁰ᵣᵢ𝓰ₕₜ₍ₒₓ₎ - E⁰ₗₑ𝒻ₜₜ₍ᵣₑ𝒹₎",
    op4: "E⁰𝒸ₑₗₗ = E⁰ₗₑ𝒻ₜₜ₍ᵣₑ𝒹₎ + E⁰ᵣᵢ𝓰ₕₜ₍ᵣₑ𝒹₎",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q13": {
    rightno: option1,
    question: "Cell electromotive force, E = ?",
    attribute: "E⁰ = Standard electromotive force, n = Number of moles, F = Faraday = 96500 C, R = 8.313 Joules, T = Temperature",
    op1: "E = E⁰ - (RT/nF) ln [K]",
    op2: "E = E⁰ - (R/nF) ln [K]",
    op3: "E = E⁰ + (0.0591/n) log [K]",
    op4: "E = E⁰ - ((0.0575/n) / log [K])",
    proof: "In thermal physics, the free energy change of a reaction can be expressed as follows:\n\nΔG = ΔG⁰ + RT ln [K]\n\nOr, alternatively:\n\n-nFE = -nFE⁰ + RT ln [K]\n\nTherefore:\n\nE = E⁰ - (RT/nF) ln [K]",
    pic: "",
    picon: false,
    picproof: "",
},

"l1c2004q14": {
    rightno: option3,
    question: "Cell electromotive force, E = ?",
    attribute: "E⁰ = Standard electromotive force, n = Number of moles, F = Faraday = 96500 C, R = 8.313 Joules, T = Temperature",
    op1: "E = E⁰ - (0.0491/nF) ln [K]",
    op2: "E = E⁰ - (0.0595/n) log [K]",
    op3: "E = E⁰ - (2.303RT / nF) log [K]",
    op4: "E = E⁰ - ((0.0495/nF) / log [K])",
    proof: "In thermal physics, the free energy change of a reaction can be expressed as follows:\n\nΔG = ΔG⁰ + RT ln [K]\n\nOr, alternatively:\n\n-nFE = -nFE⁰ + RT ln [K]\n\nTherefore:\n\nE = E⁰ - (RT/nF) ln [K] = E⁰ - (2.303RT / nF) log [K]",
    pic: "",
    picon: false,
    picproof: "",
},

"l1c2004q15": {
    rightno: option2,
    question: "Cell electromotive force, E = ?",
    attribute: "E⁰ = Standard electromotive force, n = Number of moles, F = Faraday = 96500 C, R = 8.313 Joules, T = Temperature",
    op1: "E = E⁰ - (0.0565/n) log [K]",
    op2: "E = E⁰ - (0.0591/n) log [K]",
    op3: "E = E⁰ - (0.0521/n) log [K]",
    op4: "E = E⁰ - ((0.0595/n) / log [K])",
    proof: "In thermal physics, the free energy change of a reaction can be expressed as follows:\n\nΔG = ΔG⁰ + RT ln [K]\n\nOr, alternatively:\n\n-nFE = -nFE⁰ + RT ln [K]\n\nOr:\n\nE = E⁰ - (RT/nF) ln [K] = E⁰ - (2.303RT / nF) log [K]\n\nOr:\n\nE = E⁰ - (2.303 × 8.313 × 298)/(n × 96500) log [K]\n\nTherefore:\n\nE = E⁰ - (0.0591/n) log [K] = E⁰ - (0.0591/n) log [K]",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q16": {
    rightno: option1,
    question: "The decrease in free energy, ΔG = ?",
    attribute: "n Farads = Amount of current, nF Coulombs = nF Coulombs, E₋ᶜₑₗₗ = Electromotive force, E⁰ = Standard electromotive force, R = 8.313 Joules, T = Temperature",
    op1: "ΔG = -nFE𝒸ₑₗₗ",
    op2: "ΔG = -nFE⁰𝒸ₑₗₗ",
    op3: "ΔG = nFE𝒸ₑₗₗ",
    op4: "ΔG = nF/E𝒸ₑₗₗ",
    proof: "We know that electrical work done = Amount of current × Voltage difference \n\n Or, Wₘₐₓ = Amount of current × Cell's electromotive force \n\n Or, Wₘₐₓ = nF × E = nFE𝒸ₑₗₗ \n\n Now, according to the laws of thermodynamics, the decrease in free energy due to a chemical reaction in an electrochemical cell is always equal to the electrical work done. Therefore, \n\n -ΔG = Wₘₐₓ = nFE𝒸ₑₗₗ \n\n So, \n\n ΔG = -nFE𝒸ₑₗₗ",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q16": {
    rightno: option3,
    question: "The efficiency of a fuel cell, ε = ?",
    attribute: "ΔH = Enthalpy change, ΔG = Gibbs free energy, Temperature coefficient = T(δE/δT)ₚ, n = Avogadro's number, F = Faraday = 96500 C, R = 8.313 Joules",
    op1: "ε = -ΔH/ΔG",
    op2: "ε = ΔH/ΔG",
    op3: "ε = ΔG/ΔH",
    op4: "ε = ΔGH",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q17": {
    rightno: option1,
    question: "The efficiency of a fuel cell, ε = ?",
    attribute: "ΔH = Enthalpy change, ΔG = Gibbs free energy, Temperature coefficient = T(δE/δT)ₚ, n = Avogadro's number, F = Faraday = 96500 C, R = 8.313 Joules",
    op1: "ε = E / (E - T(δE/δT)ₚ)",
    op2: "ε = E / (E - T(δE/δT))",
    op3: "ε = E / (E + T(δE/δT))",
    op4: "ε = E / (E + (TδE)ₚ)",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q18": {
    rightno: option4,
    question: "The working efficiency of a fuel cell, η = ?",
    attribute: "ΔH = Enthalpy change, ΔG = Gibbs free energy change, Temperature coefficient = T(δE/δT)ₚ, n in Farads = Amount of current passed = nF Coulombs, E𝒸ₑₗₗ = Electrolyte potential, E⁰ = Standard electrode potential",
    op1: "η = (ΔH / ΔG) × 100",
    op2: "η = (FE𝒸ₑₗₗ / ΔH) × 100",
    op3: "η = (nFE𝒸ₑₗₗ / ΔH) × 100",
    op4: "η = (-nFE𝒸ₑₗₗ / ΔH) × 100",
    proof: "η = (ΔG / ΔH) × 100 \n\n Or, η = (-nFE𝒸ₑₗₗ / ΔH) × 100",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q19": {
    rightno: option3,
    question: "The charge of an electron, e = ?",
    attribute: "F = Farad, N = Avogadro's number",
    op1: "e = N / F",
    op2: "e = -N / F",
    op3: "e = F / N",
    op4: "e = F × N",
    proof: "",
    pic: "",
    picon: false,
    picproof: "",
},


"l1c2004q20": {},