//   // l1c1003qX
//Physics 3rd

//for physics 2nd 
//template and where X stands to question number, c**** stands for chapter and subject code

"l1c1003qX" {
    rightno: option1-4, 
   question: "",  
   attribute:"", 
   op1:"",  
   op2:"", 
   op3:"", 
   op4:"", 
   proof:"N/A", 
   pic: "", 
   picon: false ,
   picproof: "",},

//starts from here

//Chapter 3

"l1c1003q1" {
    rightno: option2, 
   question: "Temperature on Resistance, α = ?",  
   attribute:"", 
   op1:"α = Rθ/R₀θ  ",  
   op2:"α =  (Rθ – R₀ )/R₀θ", 
   op3:"α = R¬θ × R₀θ", 
   op4:"α = (R₀ – Rθ )/R₀θ", 
   proof:"N/A", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q2" {
    rightno: option4, 
   question: "Which of the following is the first law of electric current?",  
   attribute:"", 
   op1:"(H₁)/(R₁) = (H₂)/(R₂) = (H₃)/(R₃) = … … … … constant",  
   op2:"(H₁)/(V₁²) = (H₂)/(V₂²) = (H₃)/(V₃²) = … … … … constant", 
   op3:"(H₁)/(t₁) = (H₂)/(t₂) = (H₃)/(t₃) = … … … … constant", 
   op4:"(H₁)/(I₁²) = (H₂)/(I₂²) = (H₃)/(I₃²) = … … … … constant", 
   proof:"If the resistance (R) of the conductor and the flow time (t) remain unchanged, then the heat generated by the electric current (h) is proportional to the square (I) of the current. \n That is, H ∝ I², when R ও t are constant. \n According to this formula, the amount of heat generated by running a stream for a certain period of time will be four times the amount of heat generated by running a flow for an equal period of time, and the amount of heat will be nine times if the flow is tripled. \n I₁, I₂, I₃, … … … flow through a conductor for the same amount of time, the amount of heat generated is H₁, H₂, H₃, … … …  respectively then according to this formula, \n (H₁)/(I₁²) = (H₂)/(I₂²) = (H₃)/(I₃²) = … … … … constant", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q3" {
    rightno: option4, 
   question: "Which of the following is the second law of electric current?",  
   attribute:"", 
   op1:"(H₁)/(V₁²) = (H₂)/(V₂²) = (H₃)/(V₃²) = … … … … constant",  
   op2:"(H₁)/(I₁²) = (H₂)/(I₂²) = (H₃)/(I₃²) = … … … … constant", 
   op3:"(H₁)/(t₁) = (H₂)/(t₂) = (H₃)/(t₃) = … … … … constant", 
   op4:"(H₁)/(R₁) = (H₂)/(R₂) = (H₃)/(R₃) = … … … … constant	", 
   proof:"If current (I) and flow time (t) remain unchanged, the heat generated by the electric current (H) is proportional to the resistance (R) of the conductor. \n That is, H ∝ R , when I ও t are constant. \n According to this formula, if the same amount of current flows through the conductors of different resistances, the heat generated will be doubled if the resistance is doubled, and the heat generated will be halved if the resistance is halved. \n If the same amount of current flows through the R₁, R₂, R₃ … … …  resistors for the same period of time, the amount of heat generated is H₁, H₂, H₃, … … … respectively then according to this formula, \n (H₁ )/(R₁) = (H₂ )/(R₂) = (H₃)/(R₃) = … … … … constant", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q4" {
    rightno: option1, 
   question: "Which of the following is the third law of electric current?",  
   attribute:"", 
   op1:"(H₁)/(t₁) = (H₂)/(t₂) = (H₃)/(t₃) = … … … … constant",  
   op2:"(H₁)/(I₁²) = (H₂)/(I₂²) = (H₃)/(I₃²) = … … … … constant", 
   op3:"(H₁)/(V₁²) = (H₂)/(V₂²) = (H₃)/(V₃²) = … … … … constant", 
   op4:"(H₁)/(R₁) = (H₂)/(R₂) = (H₃)/(R₃) = … … … … constant", 
   proof:"If the current (I) and the resistance (R) of the conductor remain unchanged, the heat generated by the electric current (H) is proportional to the flow time (t). \n That is, H ∝ t , when I ও R are constant. \n According to this formula, if the same amount of current flows through a certain conductor for different periods of time, if the duration of the flow is doubled, the heat generated will be doubled, and if the resistance is halved, the heat generated will be halved. \n If the same amount of heat flowing through a particular conductor for a period of time t₁, t₂, t₃ … … is H₁, H₂, H₃, … … … respectively, then according to this formula, \n (H₁)/(t₁) = (H₂)/(t₂) = (H₃)/(t₃) = … … … … constant", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q5" {
    rightno: option2, 
   question: "Formula of Electric current, I?",  
   attribute:"I = Electric Current, R = Resistance, r = Inner resistance, E = Energy", 
   op1:"I = E/(R-r)",  
   op2:"I = E/(R+r)", 
   op3:"I = (R - r)/E", 
   op4:"I = E² (R-r)", 
   proof:"Suppose, electric current is I. The energy of the cell is E. C provides E-joule energy to bring C charge back to A by moving it through the resistor R from point A in a full circuit. One part of this E energy is spent by V. Coulomb conducts charge from point A to point B through R and the rest of V is used to drive charge from point B to A through internal resistance r. So according to the law of the permanence of energy, \n\n E = V + V’ ----(i) \n\n But V is the voltage difference between the two ends of A and B i.e. R and V’ is the difference in voltage between the two ends of the internal resistor r. Applying Ohm’s formula we get, V = IR and V’ = Ir \n\n So, E = IR + Ir \n\n Or, I (R+r) = E \n\n So, I = E/(R+r)", 
   pic: "", 
   picon: false ,
   picproof: require('../Formula Master files/Physics 2nd/images/c1003q5.png'), },



"l1c1003q6" {
    rightno: option3, 
   question: "Electric current, I = ?",  
   attribute:"", 
   op1:"I = V/R", 
   op2:"I = G/V", 
   op3:"I = V/R", 
   op4:"I = R/V", 
   proof:"According to O’Meal’s formula, the electric current that flows through a particular conductor when the temperature is constant is equal to the voltage difference between the two ends of the conductor. \n So, I ∝ V \n Or, I = GV \n Here G is a proportional constant, called the electrical conductivity of the conductor. We put the inverse of G in the equation above R = (1)/G we get, \n I = V/R", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q7" {
    rightno: option4, 
   question: "Formula of Iₛ?",  
   attribute:"Iₛ = Current of Series combination, R = Marginal resistance, r = Inner resistance, E = Energy, n = number of terms", 
   op1:"Iₛ = nE/(nR+nr)",  
   op2:"Iₛ = (n(R+r))/E", 
   op3:"Iₛ = E/(nR+nr)", 
   op4:"Iₛ = nE/(R+nr)", 
   proof:"We know, Iₛ = Eₛ/(R+r) \n\n But since the cells are classified, the total electromotive force will be Eₛ = E + E + …… n number of terms = nE and internal resistance, rₛ = r + r + …….n number of terms = nr \n\n So, Iₛ = Eₛ/(R+nr)", 
   pic: "Formula Master files/Physics 2nd/images/c1003q7.png", 
   picon: false ,
   picproof: require('../Formula Master files/Physics 2nd/images/c1003q7.png'), },



"l1c1003q8" {
    rightno: option2, 
   question: "Formula of Iₚ?",  
   attribute:"Iₚ = Current of Parallel combination, R = Marginal resistance, r = Inner resistance, E = Energy, m = number of terms", 
   op1:"Iₚ = mE/(mR+mr)",  
   op2:"Iₚ = mE/(mR+r)	", 
   op3:"Iₚ = mE/(R+mr)", 
   op4:"Iₚ = E/(mR+r)", 
   proof:"We know, \n According to the Ohm’s formula, Iₚ = Eₚ/(R+rₚ) \n But since the cells with equal electromagnetic energy are in parallel, the total electromotive force of the coordinate cells is equal to the electromagnetic energy of any one cell. \n Meaning, Eₚ = E. And because cells are parallel, their internal barriers are also arranged in parallel, \n So, 1/rₚ  = 1/r+  1/r+⋯m number of terms \n = m/r \n So, rₚ = r/m \n Also, Iₚ = E/(R+r/m) \n or, Iₚ = mE/(mR+r)", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q9" {
    rightno: option3, 
   question: "Which one of the following is the first law of Kirchhoff’s laws?",  
   attribute:"", 
   op1:"∑IR = ∑E",  
   op2:"∑I = ∑R", 
   op3:"∑I = 0 ", 
   op4:"I = ∑RE", 
   proof:"According to Kirchhoff’s first law, \n The algebraic sum of the combined currents at any point of connection of the electrical circuit is zero. \n So, ∑I = 0", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q10" {
    rightno: option4, 
   question: "Which one of the following is the second law of Kirchhoff’s laws?",  
   attribute:"", 
   op1:"∑E =  ∑Ir",  
   op2:"∑I = 0 ", 
   op3:"∑I = ∑R", 
   op4:"∑IR = ∑E ", 
   proof:"According to Kirchhoff’s second law, \n The algebraic sum of the resistances of the different parts of a closed electrical circuit and the product of their ancillary currents is equal to the total electromotive force contained in that circuit. \n Thereby, ∑IR = ∑E", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q11" {
    rightno: option4, 
   question: "Formula of Ig?",  
   attribute:"Ig = Current of Galvanometer, I = Electricity current, S = Shunt, G = Resistance", 
   op1:"Ig =S/(G+I)",  
   op2:"Ig = S/(I+S) G", 
   op3:"Ig = S/(G+S)", 
   op4:"Ig = S/(G+S) I", 
   proof:"We know, I = Ig + Is \n We know if the voltages of points A and B are Vₐ and Vᵦ respectively, \n In the case of Galvanometers, Vₐ - Vᵦ = IgG \n And, in the case of shunts, Vₐ - Vᵦ = IₛS \n By comparison, IₛS = IgG \n Or, Iₛ/Ig  = G/S \n By adding I to both sides, \n (Iₛ + Ig)/Ig = (G + S)/S \n Or, I/Ig = (G + S)/S \n Or, Ig  = (S)/(G+S) I", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q12" {
    rightno: option3, 
   question: "Formula of  S?",  
   attribute:"S = Shunt, Ig = Current of Galvanometer, I = Electricity current, G = Resistance", 
   op1:"S = (I-Ig)/I × G",  
   op2:"S = Ig/(Ig-I) × G", 
   op3:"S = Ig/(I-Ig) × G", 
   op4:"S = (Ig/G)/(I-Ig)", 
   proof:"We know, Ig = S/(G+S) × I \n Or, (S+G)Ig = S × I  \n or, S (I-Ig) = IgG \n So, S = Ig/(I-Ig) × G", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q13" {
    rightno: option1, 
   question: "Formula of  mechanical equivalence of heat, J?",  
   attribute:"J = Mechanical equivalence of heat, V = The voltage difference between the two ends, I = Ampere flow, t = time, m = mass, s = The relative heat of the material, θ = Temperature", 
   op1:"J =	VIt/msΔt  J cal⁻¹",  
   op2:"J =  VI/msΔt  J cal⁻¹", 
   op3:"J = VIt/msΔt J Kcal⁻¹", 
   op4:"J = VΔt/msI Kcal⁻¹", 
   proof:"We know, W  = J × H 	or, J = W/H  = (VIt  J)/(H Cal) -----(i) \n Also, absorbed heat, H = msΔt -----(ii) \n From equation (i) and (ii) we get, \n J = VIt/msΔt J cal⁻¹", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q14" {
    rightno: option3, 
   question: "Formula of  Relative resistance of wire material, ρ?",  
   attribute:"ρ = Relative resistance of wire material, P = Wire resistance, L = Wire length, r = Wire radius", 
   op1:"ρ = 2πr²/L",  
   op2:"ρ = Pπr/L", 
   op3:"ρ = Pπr²/L", 
   op4:"ρ = 2Pπr²/L", 
   proof:"The resistance of a conductor to a unit of length and unit of cross section at a given temperature is called the relative resistance of the material of that conductor at that temperature. \n Therefore, we know from the source of resistance, if the resistance of the conductor is P, \n P = ρ L/A \n Or, ρ = Pπr²/L", 
   pic: "", 
   picon: false ,
   picproof: "",},



"l1c1003q15" {},

