//l0c305
"l0c305q1":{
    rightno: option3, 
    question: "ভিন্ন ভিন্ন মানের জন্য, ⁿPᵣ=?", 
    attribute:"", 
    op1:"ⁿPᵣ= n!/(n-r)",   
    op2:"ⁿPᵣ= n/(n-r)", 
    op3:"ⁿPᵣ=  n!/(n-r)!", 
    op4:"ⁿPᵣ= n!/(r-n)!", 
    proof:"\n\n আমরা জানি,\n\n ⁿPᵣ =n(n-1)(n-2) ... (n-r+1) \n\n = (n(n-1)(n-2)… (n-r+1)(n-r)(n-r-1)… 3.2.1.)/((n-r)(n-r-1)… 3.2.1) \n\n  = n!/(n-r)!", 
    pic: "", 
    picon: false ,
    picproof: "",},
  "l0c305q2":{
    rightno: option1, 
    question: "ভিন্ন ভিন্ন মানের জন্য, ⁿPₙ=? [যেখানে, n∈ N  r ≤ n]", 
    attribute:"", 
    op1:"ⁿPₙ = n!",  
    op2:"ⁿPₙ = n! (n-r)!", 
    op3:"ⁿPₙ = n!/(n-r)", 
    op4:"ⁿPₙ = n(n-r)!", 
    proof:"\n\n n হল বিন্যাসের সংখ্যা, যা বিভিন্ন জিনিসের একটি সংখ্যা থেকে সমস্ত জিনিসকে একত্রিত করছে। \n\n ⁿPₙ =n(n-1)(n-2) ... হতে n সংখ্যা পর্যন্ত \n\n =n(n-1(n-2) ... (n-n+1)=n(n-1)(n-2) ... 1 = n(n-1)(n-2) ... 3.2.1. \n\n  ∴ ⁿPₙ =n!", 
    pic: "", 
    picon: false ,
    picproof: "",},
  "l0c305q3":{
    rightno: option4, 
    question: "নিশ্চায়ক এ, n! = ?", 
    attribute:"", 
    op1:"n! = n/((n-1)! ) =  n/((n-1)(n-2)! )",  
    op2:"n! = (n-1)! = (n-1)(n-2)! Etc.", 
    op3:"n! = n(n-1)! = n(n-1)(n-2)!  Etc.", 
    op4:"n! = n(n-1)! = n(n-1)(n-2)! Etc.", 
    proof:"\n\n 1 থেকে n পর্যন্ত সমস্ত স্বাভাবিক সংখ্যার পরপর গুণফল সাধারণত n! দ্বারা প্রকাশ করা হলে n! = n(n-1)(n-2)(n-3)... 3.2.1 = n(n-1)! \n\n =n(n-1)(n-2)!=n(n-1)(n-2)....(n-r=1)(n-r)! \n\n উদাহরণ হিসেবে, 6! = 6.5.4.3.2.1 \n\n =6.5!=6.5.4!", 
    pic: "", 
    picon: false ,
    picproof: "",},
  "l0c305q4":{
    rightno: option2, 
    question: "কিছু সংখ্যা অভিন্ন এবং বাকিসব ভিন্ন এর ক্ষেত্রে, বিন্যাস নম্বর X = ?", 
    attribute:"", 
    op1:"X = n/pqr!",  
    op2:"X = n!/p!q!r!", 
    op3:"X = n/pqr", 
    op4:"X = n! (p!q!r!)", 
    proof:"\n\n মনে করি, n জিনিসের সংখ্যার মধ্যে, p সংখ্যা প্রথম ধরনের, q সংখ্যা দ্বিতীয় ধরনের, r সংখ্যা তৃতীয় ধরনের এবং বাকি সকল জিনিস ভিন্ন.\n\n যদি p, p এর মতো একই সংখ্যক অভিন্ন জিনিস দ্বারা প্রতিস্থাপিত হয়, তাহলে এই পৃথক জিনিসগুলি p! দ্বারা প্রতিস্থাপিত হবে যাহা কিছু উপায়ে সাজানো যায়। অর্থাৎ, অর্থাৎ, ডায়াগনস্টিক ফরম্যাট এক থেকে p! পর্যন্ত উপলব্ধ বিন্যাস সংখ্যা. এখন নির্ধারিত নাম্বারটিকে x দ্বারা সূচিত করা হলে, p সংখ্যাটি আলাদাভাবে ধরে রাখলে মোট ফরম্যাট সংখ্যা তৈরি হবে x × p! \n\n অনুরূপে x × p! যদি একই বিন্যাসের প্রতিটি q একই সংখ্যক পৃথক আইটেম দ্বারা প্রতিস্থাপিত হয়, মোট ফরম্যাট নম্বর হবে x × p! × q! \n\n অনুরূপে x × p! × q! × r! লেআউটের মোট সংখ্যা হল x × p! × q! × r! \n\n এখন সবকিছুই ভিন্ন বা অমিল. সুতরাং, n সংখ্যার সমস্ত জিনিস একেবারে বিন্যাস নম্বর n! হবে \n\n ∴ x × p! × q! × r! = n! অতএব, x= n!/p!q!r! \n\n ∴ x = n!/p!q!r!", 
    pic: "", 
    picon: false ,
    picproof: "",},
  "l0c305q5":{
    rightno: option1, 
    question: "ⁿCᵣ = ? ", 
    attribute:"", 
    op1:"ⁿCᵣ = n!/r!(n-r)!",  
    op2:"ⁿCᵣ = n!/(n-r)!", 
    op3:"ⁿCᵣ = n!r!(n-r)!", 
    op4:"ⁿCᵣ = n!r!/(n-r)!", 
    proof:"\n\n The number of nCr assemblies in which a will always be a is n-1Cr-1 , because in each of the n-1Cr-1 assemblies with a (r-1) number of letters from each of the remaining (n-1) letters except a If included, the total number of characters in that assembly will be r. \n\n Similarly, all the assemblies that have b, c, d ... will have n-1Cr-1 So, if all the assemblies are written with the r number every time from n different letters, then each letter will have ⁿ⁻¹C ᵣ₋₁ number in those assemblies.\n\n Since the total number of letters is n therefore the number of letters in the written assemblies = n × ⁿ⁻¹C ᵣ₋₁ ... (i) \n\n Again each assembly has the number of r so the total number of letters in the assembly, nCr =  r × ⁿCᵣ ... (ii) \n\n So, from (i) I (ii)  r× ⁿCᵣ = n × ⁿ⁻¹Cᵣ₋₁  \n\n ∴ ⁿCᵣ = n/r × ⁿ⁻¹C ᵣ₋₁ ... (1) \n\n Similarly, ⁿ⁻¹C ᵣ₋₁  = n-1/r-1 × ⁿ⁻²C ᵣ₋₂ ... (2) \n\n ⁿ⁻²C ᵣ₋₂ = n-2/r-2 × ⁿ⁻³C ᵣ₋₃ ... (3) \n\n ............................................................................. \n\n ⁿ⁻ʳ⁺²C₂ = n-r+2/2 × ⁿ⁻ʳ⁺¹C₁ ... (n) \n\n By multiplying all from (1) to (n) together and subtracting the common product from both sides of the product we get, \n\n ⁿCᵣ= n(n-1)(n-2)....(n-r+2)/r(r-1)(r-2).....2 × ⁿ⁻ʳ⁺¹Cᵣ  \n\n Now ⁿ⁻ʳ⁺¹C₁ means (n - r + 1) the number of assemblies by taking 1 from each number of things. Thus, ⁿ⁻ʳ⁺¹C₁ = n-r + 1 \n\n ∴ⁿCᵣ = n(n-1)(n-2)...(n-r+2)(n-r+1)/r! \n\n =(n(n-1)(n-2)….(n-r+2)(n-r+1)(n-r)!)/r!(n-r)! \n\n =n!/r!(n-r)!", 
    pic: "", 
    picon: false ,
    picproof: "",},
  "l0c305q6":{
    rightno: option2, 
    question: "সম্পূরক সমাবেশে, ⁿCᵣ = ?", 
    attribute:"", 
    op1:"ⁿCᵣ = ⁿCₙ - rCr",  
    op2:"ⁿCᵣ = ⁿCₙ₋ᵣ ", 
    op3:"ⁿCᵣ = rCr - ⁿCₙ", 
    op4:"ⁿCᵣ = nCr-n", 
    proof:"\n\n আমরা জানি, ⁿCᵣ = n!/r!(n-r)!  and ⁿCₙ₋ᵣ = n!/(n-r)!(n-n+r)! = n!/(n-r)!r! \n\n সারারণত, ⁿCᵣ এবং ⁿCₙ₋ᵣ একে অপরের পরিপূরক। \n\n ∴ⁿCᵣ = ⁿCₙ₋ᵣ", 
    pic: "", 
    picon: false ,
    picproof: "",},
  "l0c305q7":{
    rightno: option2, 
    question: "সম্পূরক সমাবেশে, ⁿ⁺¹Cᵣ = ?", 
    attribute:"", 
    op1:"ⁿ⁺¹Cᵣ = ⁿCᵣ  -  ⁿCᵣ₋₁",  
    op2:"ⁿ⁺¹Cᵣ = ⁿCᵣ + ⁿCᵣ₋₁", 
    op3:"ⁿ⁺¹Cᵣ = ⁿCᵣ - 1 - ⁿCᵣ", 
    op4:"ⁿ⁺¹Cᵣ = ⁿCn  + ʳCᵣ", 
    proof:"\n\n ⁿCᵣ + ⁿCᵣ₋₁ = n!/r!(n-r)! + n!/(r-1)(n-r+1)! \n\n =(n!/r.(r-1)!(n-r)!+n!)/((r-1)!(n-r+1).(n-r)!) \n\n =n!/(r-1)!(n-r)!  {(1/r+1)/(n-r+1) } = n!/(r-1)1(n-r)! . (n+1)/r(n-r+1) \n\n =(n+1)!/(n-r+1)!r! = (n+1)!/r!{(n+1)-r}! = n+¹Cᵣ", 
    pic: "", 
    picon: false ,
    picproof: "",},

  "l0c305q8":{},
