//Chapter 9 - Differntiation

//Template
"l0c309qX":{
    rightno: option3,
    question: "",  
    attribute:"", 
     op1:"",  
    op2:"", 
    op3:"", 
    op4:"", 
    proof:"\n\n ",
     pic: "",         
     picon: false ,
    picproof: require('../assets/Picturename.png'), },

 "l0c309qX":{
    rightno: option3,
    question: "",  
    attribute:"", 
     op1:"",  
    op2:"", 
    op3:"", 
    op4:"", 
    proof:"\n\n ",
     pic: "",         
     picon: false ,
    picproof: "",},

    
    //Starts here///////


 "l0c309q1":{
    rightno: option4,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (u ± v) = ?",  
    attribute:"", 
    op1:"d/dx (u ± v) = d/dx (u) - d/dx (v)",  
    op2:"d/dx (u ± v) = d/dx (u) + d/dx (v)", 
    op3:"d/dx (u ± v) = v d/dx(u) ± u d/dx(v)", 
    op4:"d/dx (u ± v) = d/dx (u) ± d/dx (v)", 
    proof:"\n\n মনে করি, u এবং y উভয়ে x  এর ফাংশন । \n ধরি, y = u ± v, ... (i) তাহলে y , x এর ফাংশন। \n মনে করি, x  এর অতি সামান্য বৃদ্ধি Ax  এর জন্য y , u , v এর অনুরূপ বৃদ্ধি যথাক্রমে Δy , Δu , Δv , যারা যথেষ্ট ক্ষুদ্র। \n ∴ y = u ± v, থেকে আমরা পাই,  y + Δy = (u + Δu) ± (v + Δv) ... (ii) (ii) থেকে (i) বিয়োগ করে, Δy = Δu  ± Δv \n ∴ Δy/Δx  = Δu/Δx ± Δv/Δx    [ উভয়পক্ষকে Δx দ্বারা ভাগ করে ] \n সুতরাং, lim┬(x→0)⁡(Δy/Δx) = (lim⁡ )┬(x→0)⁡(Δy/Δx) = (lim⁡)┬(x→0)⁡(Δv/Δx) \n ∴ dy/dx = du/dx ± dv/dx \n অর্থাৎ, d/dx (u ± v) = d/dx (u) ± d/dx (v)",
     pic: "",         
     picon: false ,
    picproof: "",},


 "l0c309q2":{
    rightno: option1,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (uv) = ?",  
    attribute:"", 
    op1:"d/dx (uv)  = v d/dx(u) + u d/dx(v)",  
    op2:"d/dx (uv)  = d/dx (u) + d/dx (v)", 
    op3:"d/dx (uv)  = v d/dx(u) - u d/dx(v)", 
    op4:"d/dx (uv)  = u d/dx(v) - v d/dx(u)", 
    proof:"\n\n মনে করি, y = uv ... (i), যেখানে a এবং y এর উভয়ে x এর ফাংশন । তাহলে, y হবে x এর ফাংশন। এখন x এর অতি সামান্য বৃদ্ধি Δx এর জন্য y, u, v এর অনুরূপ বৃদ্ধি হবে যথাক্রমে Δy, Δu, Δv । \n ∴ y + Δy = (u + Δu) (v + Δv)	 [∵ ধরি, y = u v] \n = u v + u. Δv + v. Δu + (Δu) (Δv) ... (ii) \n (ii) থেকে (i) বিয়োগ করে আমরা পাই, \n Δy = u. Δv + v . Δu + (Δu) (Δv) \n ∴ Δy/Δx = u. Δv/Δx + v. Δu/Δx + Δu. Δv/Δx \n ∴ lim₍Δₓ→₀₎ (Δy/Δx) = lim₍Δₓ→₀₎  (u.Δv/Δx) + lim₍Δₓ→₀₎ (v.Δu/Δx) + lim₍Δₓ→₀₎ (Δu.Δv/Δx) [লিমিটের সূত্র থেকে] \n = u. lim₍Δₓ→₀₎ (Δv/Δx) + v. lim₍Δₓ→₀₎  (Δu/Δx  ) + lim₍Δₓ→₀₎ (Δu) × lim₍Δₓ→₀₎  (Δv/Δx)   … ….(iii) \n যেহেতু, Δx→ 0 then, Δu → 0; ∴ 〖lim〗_(Δx→0) Δu = 0 \n অর্থাৎ, lim₍Δₓ→₀₎ (Δu) × lim₍Δₓ→₀₎ (Δv/Δx) = 0 \n সুতরাং, (iii) থেকে সংজ্ঞানুসারে \n d/dx (y) = u dv/dx + v du/dx + 0 \n ∴ d/dx (uv) = v d/dx(u) + u d/dx(v)",
     pic: "",         
     picon: false ,
    picproof: "",},


 "l0c309q3":{
    rightno: option2,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (u/v) =  (v.du/dx  - u.dv/dx)/v²",  
    attribute:"", 
    op1:"d/dx (u/v) = (v.du/dx  + u.dv/dx)/v² ",  
    op2:" d/dx (u/v) =  (v.du/dx  - u.dv/dx)/v²	", 
    op3:"d/dx (u/v) = v d/dx(u) × u d/dx(v)", 
    op4:"d/dx (u/v) = (v.du/dx  + u.dv/dx)/u² ", 
    proof:"\n\n মনে করি, y = u/v ... (i), যেখানে u এবং y এর উভয়ে x এর ফাংশন। তাহলে, y হবে x এর ফাংশন। মনে করি, x এর অতি সামান্য বৃদ্ধি Δx এর জন্য y, u, v এর অনুরূপ বৃদ্ধি যথাক্রমে Δy, Δu, Δv. \n ∴ y + Δy = (u+Δu)/(v+Δv)   ... (ii) \n (ii) থেকে (i) বিয়োগ করে আমরা পাই, Δy = (u+Δu)/(v+Δv) - u/v = (vΔu - uΔy)/(v(v+Δv)) \n ∴ Δy/Δx =	(y.Δu/Δx  – u.Δv/Δx)/(v(v + Δv))		[উভয়পক্ষকে Δx দিয়ে ভাগ করে] \n ∴ lim₍Δₓ→₀₎ (Δy/Δx) =  (lim₍Δₓ→₀₎  (Δu/Δx) - lim₍Δₓ→₀₎  (u.Δu/Δx))/(lim₍Δₓ→₀₎  {v (v+ Δv)})	[লিমিটের সূত্র থেকে] \n এখন সংজ্ঞানুসারে, d/dx (y) = (v.du/dx  - u.dv/dx)/v²  		[যেহেতু, Δx → 0 হলে, Δv → 0] \n সুতরাং, d/dx (u/v) = (v.du/dx  - u.dv/dx)/v²",
     pic: "",         
     picon: false ,
    picproof: "",},


 "l0c309q4":{
    rightno: option4,
    question: "অন্তরজ নির্ণয়ের সূত্রের নিচের কোনটি সঠিক?",  
    attribute:"", 
    op1:"dz = f (x) dx",  
    op2:"dz = f′ (x)", 
    op3:"dz = f′ (z) dx", 
    op4:"dz = f′ (x) dx", 
    proof:"\n\n",
     pic: "",         
     picon: false ,
    picproof: "",},


 "l0c309q5":{
    rightno: option1,
    question: "lim {u(x) ± v(x) ± w(x)} = ?",  
    attribute:"u, v, w হচ্ছে x এর ফাংশন", 
    op1:"lim {u(x) ± v(x) ± w(x)} = lim {u(x)} ± lim {v(x)} ± lim {w(x)}",  
    op2:"lim {u(x) ± v(x) ± w(x)} = lim {x(u)} ± lim {x(v)} ± lim {x(w)}", 
    op3:"lim {u(x) ± v(x) ± w(x)} = lim {x(u+v+w)}", 
    op4:"lim {u(x) ± v(x) ± w(x)} =lim {uvw(x)}",
    proof:"\n\n লিমিটের মৌলিক একটি ধর্মঃ দুইটি বা ততোধিক (সসীম সংখ্যক) ফাংশনের বীজগনিতীয় সমষ্টির লিমিট তাদের প্রত্যেকের আলাদা আলাদা লিমিটের বীজগনিতীয় সমষ্টির সমান। তাই, \n lim {u(x) ± v(x) ± w(x)} = lim {u(x)} ± lim {v(x)} ± lim {w(x)}",
     pic: "",         
     picon: false ,
    picproof: "",},

"l0c309q6":{
    rightno: option2,
    question: "lim {u(x) × v(x)} = ?",  
    attribute:"", 
    op1:"lim {u(x) × v(x)} = lim {v(x)} - lim {u(x)}",  
    op2:"lim {u(x) × v(x)} = lim {u(x)} × lim {v(x)}", 
    op3:"lim {u(x) × v(x)} = lim {uv(x)}", 
    op4:"lim {u(x) × v(x)} = lim {u(x)} / lim {v(x)}", 
    proof:"\n\n দুইটি ফাংশনের গুণফলের লিমিট, তাদের আলাদা আলাদা লিমিটের গুণফলের সমান। তাই, \n lim {u(x) × v(x)} = lim {u(x)} × lim {v(x)}",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q7":{
    rightno: option3,
    question: "lim { u(x)/v(x) } = ?",  
    attribute:"", 
    op1:"lim { u(x)/v(x) } = lim {u(x)} ± lim {v(x)} ± lim {w(x)}",  
    op2:"lim { u(x)/v(x) } = lim (u/v)x", 
    op3:"lim { u(x)/v(x) } = lim {u(x)} / lim {v(x)}", 
    op4:"lim { u(x)/v(x) } = lim {v(x)} / lim {u(x)}", 
    proof:"\n\n দুইটি ফাংশনের ভাগফলের লিমিট, তাদের লিমিটের ভাগফলের সমান, যদি হরের লিমিট শূন্য না হয়। তাই, \n lim { u(x)/v(x) } = lim {u(x)} / lim {v(x)}",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q8":{
    rightno: option2,
    question: "d/dx (xⁿ) = ?",  
    attribute:"", 
    op1:"d/dx (xⁿ) = nxⁿ⁺¹",  
    op2:"d/dx (xⁿ) = nxⁿ⁻¹", 
    op3:"d/dx (xⁿ) = nxⁿ⁻¹ / 2", 
    op4:"d/dx (xⁿ) = nxⁿ⁻¹ / n-1", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q9":{
    rightno: option4,
    question: "logₓa = ?",  
    attribute:"", 
    op1:"logₓa = lna / logₑx",  
    op2:"logₓa = logₑx / lna", 
    op3:"logₓa = logₐe lnx", 
    op4:"logₓa = logₑa / lnx", 
    proof:"logₓa = logₑa × logₓe = logₑa × (1 / logₑx)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q10":{
    rightno: option3,
    question: "logₐx = ?",  
    attribute:"", 
    op1:"logₐx = logₑa / lnx",  
    op2:"logₐx = logₑa lnx", 
    op3:"logₐx = logₐe lnx", 
    op4:"logₐx = logₐe logₐx", 
    proof:"logₐx = logₐe × logₑx = logₐe lnx",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q11":{
    rightno: option4,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (sin⁻¹x) = ?        [-1 < x < 1]",  
    attribute:"", 
    op1:"d/dx (sin⁻¹x) = 1 / √(x²-1)",  
    op2:"d/dx (sin⁻¹x) = 1 / (1 + x²)", 
    op3:"d/dx (sin⁻¹x) = √(1+x²)", 
    op4:"d/dx (sin⁻¹x) = 1 / √(1-x²)", 
    proof:"মনে করি, y = sin⁻¹x. তাহলে x = siny....(i) \n (i) নং এর উভয়পক্ষে y এর প্রেক্ষিতে অন্তরীকরণ করে আমরা পাই, \n dx/dy = cosy \n অতএব, dy/dx = 1/cosy   [dy/dx = 1/(dx/dy)] \n অর্থ্যাৎ, d/dx(sin⁻¹x) = 1/cosy = 1 / √(1-sin²y) = 1 / √(1-x²) \n সুতরাং, d/dx (sin⁻¹x) = 1 / √(1-x²)  [-1 < x < 1] ",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q12":{
    rightno: option3,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (cos⁻¹x) = ?",  
    attribute:"", 
    op1:"d/dx (cos⁻¹x) = √(1+x²)",  
    op2:"d/dx (cos⁻¹x) = 1 / (1+x²)", 
    op3:"d/dx (cos⁻¹x) = 1 / √(1-x²)", 
    op4:"d/dx (cos⁻¹x) = 1 / √(x²-1)", 
    proof:"মনে করি, y = cos⁻¹x. অতএব, dx/dy = -siny = - √(1-cos²y) = - √(1-x²) \n আবার, dy/dx = 1/(dx/dy) = - 1/√(1-x²) \n অর্থ্যাৎ, d/dx (cos⁻¹x) = d/dx (cos⁻¹x) = 1 / √(1-x²)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q13":{
    rightno: option2,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (tan⁻¹x) = ?",  
    attribute:"", 
    op1:"d/dx (tan⁻¹x) = √(1+x²)",  
    op2:"d/dx (tan⁻¹x) = 1 / (1+x²)", 
    op3:"d/dx (tan⁻¹x) = 1 / √(x²-1)", 
    op4:"d/dx (tan⁻¹x) = 1 / √(1-x²)", 
    proof:"মনে করি, y = tan⁻¹x. তাহলে, x = tany. \n অতএব, dx/dy (sec²y) = 1 + tan²y = 1 + x² \n বা, dy/dx = 1/(dx/dy) = 1 / (1+x²) \n অর্থাৎ, d/dx (tan⁻¹x) = 1 / (1+x²)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q14":{
    rightno: option2,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx ( cot⁻¹ 1-x / 1+x ) = ?",  
    attribute:"", 
    op1:"d/dx ( cot⁻¹ 1-x / 1+x ) = 1 / (1-x²)",  
    op2:"d/dx ( cot⁻¹ 1-x / 1+x ) = - 1 / (1+x²)", 
    op3:"d/dx ( cot⁻¹ 1-x / 1+x ) = - 1 / (1-x²)", 
    op4:"d/dx ( cot⁻¹ 1-x / 1+x ) = √(1+x²) / √(1-x²)", 
    proof:"মনে করি, y = cot⁻¹ 1-x / 1+x = tan⁻¹ 1-x / 1+x = tan⁻¹ 1 - tan⁻¹ x = π/4 - tan⁻¹ x \n অতএব, dy/dx = 0 - 1 / (1 + x²) = - 1 / (1 + x²)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q15":{
    rightno: option1,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx tan⁻¹ 1 / (√x² - 1) = ? ",  
    attribute:"", 
    op1:"d/dx tan⁻¹ 1 / (√x² - 1) = - 1 / x√(x²-1)",  
    op2:"d/dx tan⁻¹ 1 / (√x² - 1) = 1 / x√(x²-1)", 
    op3:"d/dx tan⁻¹ 1 / (√x² - 1) = - 1 / (x²+1)", 
    op4:"d/dx tan⁻¹ 1 / (√x² - 1) = 1 / √(1-x²)", 
    proof:"মনে করি, y = tan⁻¹ 1 / √x² - 1 = tan⁻¹ (1 / √sec²θ - 1)  [x = secθ ধরে] \n = tan⁻¹ 1/tanθ = tan⁻¹ cotθ = tan⁻¹ tan(π/2 - θ) = π/2 - sec⁻¹x \n সুতরাং, d/dx tan⁻¹ 1 / (√x² - 1) = - 1 / x√(x²-1)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q16":{
    rightno: option1,
    question: "নিচের কোনটি ম্যাকলরিনের ধারা?",  
    attribute:"", 
    op1:"f(x) = f(0) + xf'(0) + x²/2! fⁿ(0) + x³/3! fⁿ'(0)+...+ xⁿ/n! fⁿ(0) +...∞",  
    op2:"dz = f′ (x) dx", 
    op3:"Sₙ = 1/d ln [ (2a + (2n - 1) d) / (2a - d) ]", 
    op4:"Sₙ = a / (1 - r)", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q17":{
    rightno: option2,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (cosx) = ?",  
    attribute:"", 
    op1:"d/dx (cosx) = sinx",  
    op2:"d/dx (cosx) = -sinx", 
    op3:"d/dx (cosx) = ", 
    op4:"d/dx (cosx) = ", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q18":{
    rightno: option3,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (tanx) = ?",  
    attribute:"", 
    op1:"d/dx (tanx) = 1 / √(1-x²)",  
    op2:"d/dx (tanx) = - sec²x cot²x", 
    op3:"d/dx (tanx) = sec²x", 
    op4:"d/dx (tanx) = -sec²x", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q19":{
    rightno: option4,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (cotx) = ?",  
    attribute:"", 
    op1:"d/dx (cotx) = -sec²x",  
    op2:"d/dx (cotx) = tanx cotx", 
    op3:"d/dx (cotx) = ln(cosec²x)", 
    op4:"d/dx (cotx) = -cosec²x", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q20":{
    rightno: option3,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (secx) = ?",  
    attribute:"", 
    op1:"d/dx (secx) = - tanx",  
    op2:"d/dx (secx) = - sec²x tanx", 
    op3:"d/dx (secx) = secx tanx ", 
    op4:"d/dx (secx) = tanx", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q21":{
    rightno: option2,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (cosecx) = ?",  
    attribute:"", 
    op1:"d/dx (cosecx) = - cosec²x cotx",  
    op2:"d/dx (cosecx) = - cosecx cotx", 
    op3:"d/dx (cosecx) = 1 / tan²x", 
    op4:"d/dx (cosecx) = -sinx", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q22":{
    rightno: option1,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (ln x) = ?",  
    attribute:"", 
    op1:"d/dx (ln x) = 1/x",  
    op2:"d/dx (ln x) = 1", 
    op3:"d/dx (ln x) = x", 
    op4:"d/dx (ln x) = 0", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q23":{
    rightno: option4,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (sinx) = ?",  
    attribute:"", 
    op1:"d/dx (sinx) = cosx",  
    op2:"d/dx (sinx) = -sinx", 
    op3:"d/dx (sinx) = -cosecx", 
    op4:"d/dx (sinx) = sec²x", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q24":{
    rightno: option3,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (eˣ) = ?",  
    attribute:"", 
    op1:"d/dx (eˣ) = 1/x",  
    op2:"d/dx (eˣ) = lneˣ", 
    op3:"d/dx (eˣ) = eˣ", 
    op4:"d/dx (eˣ) = 1", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q25":{
    rightno: option2,
    question: "অন্তরজ নির্ণয়ের সূত্রঃ d/dx (aˣ) = ?",  
    attribute:"", 
    op1:"d/dx (aˣ) =  x lna",  
    op2:"d/dx (aˣ) = aˣ lna", 
    op3:"d/dx (aˣ) = aˣ", 
    op4:"d/dx (aˣ) = 1", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l0c309q26":{},
