"l0c303q1": {
	rightno: option2,
		question: "দ্বিতীয় চতুর্ভাগে (-x, y) বিন্দুর ক্ষেত্রে, θ = ?",
			attribute: "0 ≤ θ ≤ 2π অথবা, -π < θ ≤ π",
				op1: "θ = tan⁻¹ y/-x = π/2 - tan⁻¹ y/x",
					op2: "θ = tan⁻¹ y/-x = π - tan⁻¹ y/x",
						op3: "θ = tan⁻¹ -y/x = π - tan⁻¹ y/-x",
							op4: "θ = tan⁻¹ y/-x = π + tan⁻¹ y/x",
								proof: "নাই",
									pic: "",
										picon: false,
											picproof: "",},
"l0c303q2": {
	rightno: option1,
		question: "তৃতীয় চতুর্ভাগে (-x, -y) বিন্দুর ক্ষেত্রে, θ = ?",
			attribute: "0 ≤ θ < 2π",
				op1: "θ = tan⁻¹ -y/-x = π + tan⁻¹ y/x ",
					op2: "θ = tan⁻¹ -y/-x = π - tan⁻¹ y/x ",
						op3: "θ = tan⁻¹ y/x = π + tan⁻¹ -y/-x ",
							op4: "θ =  tan⁻¹ -y/-x = π + tan y/x ",
								proof: "নাই",
									pic: "",
										picon: false,
											picproof: "",},
"l0c303q3": {
	rightno: option4,
		question: "চতুর্থ চতুর্ভাগে (x, -y) বিন্দুর ক্ষেত্রে, θ = ?",
			attribute: "0 ≤ θ < 2π",
				op1: "θ = tan⁻¹ -y/x = π - tan⁻¹ y/x",
					op2: "θ = tan⁻¹ -y/x = 2π + tan⁻¹ y/x",
						op3: "θ = tan⁻¹ -y/x = 2π - tan⁻¹ -y/x",
							op4: "θ = tan⁻¹ -y/x = 2π - tan⁻¹ y/x",
								proof: "নাই",
									pic: "",
										picon: false,
											picproof: "",},
"l0c303q4": {
	rightno: option1,
		question: "চতুর্থ চতুর্ভাগে (x, -y) বিন্দুর ক্ষেত্রে, θ = ? ",
			attribute: "-π < θ ≤ π ",
				op1: "θ = tan⁻¹ -y/x = - tan⁻¹ y/x ",
					op2: "θ = tan⁻¹ -y/x = tan⁻¹ y/x ",
						op3: "θ = tan⁻¹ -y/x = tan⁻¹ -y/x",
							op4: "θ = tan⁻¹ -y/x = - tan⁻¹-y/x",
								proof: "নাই",
									pic: "",
										picon: false,
											picproof: "",},
"l0c303q5": {
	rightno: option3,
		question: "(0, 0) বিন্দু এবং (x, y) বিন্দুর মধ্যবর্তী দূরত্ব, r = ?",
			attribute: "",
				op1: "r = √(y² - x²)",
					op2: "r = √(x² - y²)",
						op3: "r = √(x² + y²)",
							op4: "r = √(x + y)",
								proof: "\n\n cos θ = ভেক্টর / P বিন্দুর ব্যাসার্ধ ভেক্টর = x/r \n\n সুতরাং, x = r cos θ......(i) \n\n এবং, sin θ = কোটি / P বিন্দুর ব্যাসার্ধ ভেক্টর = y/r \n\n সুতরাং, y = r sin θ......(ii) \n\n (i) এবং (ii) কে বর্গ করে আমরা পাই, \n\n x² + y² = r² (cos θ)² + r² (sin θ)² \n\n = r²(cos²θ + sin² θ) = r². 1 =  r² \n\n অতএব, r = √(x² + y²)",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q5.png'),},
"l0c303q6": {
	rightno: option4,
		question: "যদি দুটি বিন্দুর পোলার স্থানাঙ্ক (r₁, θ₁) এবং (r₂, θ₂) হয় তাহলে, তাদের মধ্যবর্তী দূরত্ব = ?",
			attribute: "A (r₁, θ₁), B (r₂, θ₂), AB = A এবং B এর মধ্যবর্তী দূরত্ব",
				op1: "AB = r₁² + r₂² - 2r₁r₂ cos (θ₁ - θ₂)",
					op2: "AB = √{r₁² - r₂² + 2r₁r₂ cos (θ₁ - θ₂)}",
						op3: "AB = √{r₁² - r₂²  - 2r₁r₂ sin (θ₁ - θ₂)}",
							op4: "AB = √{r₁² + r₂² - 2r₁r₂ cos (θ₁ - θ₂)} ",
								proof: "\n\n A (r₁, θ₁) এবং B (r₂, θ₂) বিন্দুর কার্তেসিয়ান স্থানাঙ্ক যথাক্রমে A (r₁ cosθ₁, r₁ sinθ₁) এবং B (r₂ cosθ₂, r₂ sinθ₂). \n\n সুতরাং, AB = √{(r₁ cosθ₁ - r₂ cosθ₂)² + (r₁ sinθ₁ - r₂ sinθ₂)²} \n\n =√{r₁² (cos²θ₁ + sin²θ₁) + r₂² (cos²θ₂ + sin²θ₂) - 2r₁r₂r₁ (cosθ₁ cosθ₂ + sinθ₁ sinθ₂)}  \n\n =  √{r₁² + r₂² - 2r₁r₂ cos (θ₁ - θ₂)}",
									pic: "",
										picon: false,
											picproof: "",},
"l0c303q7": {
	rightno: option1,
		question: "m₁: m₂ অনুপাতে অন্তর্বিভক্তকারী বিন্দুর স্থানাঙ্ক, (x, y) = ?",
			attribute: "(x₁, y₁), (x₂, y₂) দুইটি বিন্দু এবং এই সংযোগকারী লাইনগুলি m₁: m₂ অনুপাতে অন্তর্বিভক্ত করলে, রেখা = (x, y)",
				op1: "(x, y) =  (m₁x₂ + m₂x₁ / m₁ + m₂, m₁y₂ + m₂y₁ / m₁ + m₂)",
					op2: "(x, y) = (m₁x₁ + m₂x₂ / m₁ + m₂, m₁y₁ + m₂y₂ / m₁ + m₂)",
						op3: "(x, y) = (m₁x₂ - m₂x₁ / m₁ + m₂, m₁y₂ - m₂y₁ / m₁ + m₂)",
							op4: "(x, y) = (m₁x₂ + m₂x₁ / m₁ - m₂, m₁y₂ + m₂y₁ / m₁ - m₂)",
								proof: "\n\n এখানে, OP = x₁,  AP = y₁ \n\n OQ = x₂, BQ = y₂ \n\n OR = x,  CR = y \n\n এখন, \n\n যেহেতু ꕔACS and ꕔBCT অনুরূপ, \n\n AS/CT = CS/BT = AC/CB = m₁/m₂...... (i) \n\n আবার, AS = PR = OR - OP = x - x₁ \n\n এবং,  CT = RQ = OQ - OR = x₂ - x  \n\n তাই (i) হতে বলা যায়, AS/CT = m₁/m₂ \n\n বা, x - x₁/ x₂ - x = m₁/m₂ \n\n বা, m₂x - m₂x₁ = m₁x₂ - m₁x \n\n বা, (m₁ + m₂) x = m₁x₂ + m₂x₁ \n\n সুতরাং, x = m₁x₂ + m₂x₁ / m₁ + m₂ \n\n এছাড়াও, CS = CR - RS = CR - PA = y - y₁ [ RS = PA] \n\n এবং, BT = QB - QT = QB - CR = y₂ - y [QT = CR] \n\n সুতরাং (i) হতে আমরা পাই, CS/BT = m₁/m₂ \n\n বা, y - y₁ / y₂ - y = m₁/m₂ \n\n বা, m₂y - m₂y₁ = m₁y₂ - m₁y \n\n বা, (m₁ + m₂) y = m₁y₂ + m₂y₁ \n\n এবং, y = m₁y₂ + m₂y₁ / m₁ + m₂ \n\n অতএব (x, y) =  (m₁x₂ + m₂x₁ / m₁ + m₂, m₁y₂ + m₂y₁ / m₁ + m₂)",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q7.png'),},

"l0c303q8": {
	rightno: option3,
		question: "m₁: m₂ অনুপাতে বহির্বিভক্তকারী বিন্দুর স্থানাঙ্ক, (x, y) = ?",
			attribute: ": (x₁, y₁), (x₂, y₂) দুইটি বিন্দু এবং এই সংযোগকারী লাইনগুলি m₁: m₂ অনুপাতে বহির্বিভক্ত করলে, রেখা = (x, y)",
				op1: "(x, y) = (m₁x₂ + m₂x₁ / m₁ - m₂, m₁y₂ + m₂y₁ / m₁ - m₂)",
					op2: "(x, y) = (m₁x₂ + m₂x₁ / m₁ + m₂, m₁y₂ + m₂y₁ / m₁ + m₂)",
						op3: "(x, y) = (m₁x₂ - m₂x₁ / m₁ - m₂, m₁y₂ - m₂y₁ / m₁ - m₂)",
							op4: "(x, y) = (m₁x₂ - m₂x₁ / m₁ + m₂, m₁y₂ - m₂y₁ / m₁ + m₂)",
								proof: "\n\n PR : QR = m₁ / m₂ \n\n বা, PR / QR = m₁ / m₂ \n\n এখানে, ꕔPRS and ꕔQRT are similar  \n\n সুতরাং, PS / QT = RS / RT = PR / QR = m₁ / m₂......(i) \n\n (i) হতে, PS / QT =  m₁ / m₂ \n\n বা, x - x₁ / x - x₂ = m₁ / m₂  \n\n বা, m₁x - m₁x₂ = m₂x - m₂x₁ \n\n বা, (m₁ - m₂)x = m₁x₂ - m₂x₁ \n\n সুতরাং, x = m₁x₂ - m₂x₁ / m₁ - m₂ \n\n আবার (i) হতে, RS / RT = m₁ / m₂ \n\n বা, y - y₁ / y - y₂ = m₁ / m₂ \n\n বা, m₁y - m₁y₂ = m₂y - m₂y₁ \n\n বা, (m₁ - m₂) y = m₁y₂ - m₂y₁ \n\n  সুতরাং, y = m₁y₂ - m₂y₁ / m₁ - m₂ \n\n সুতরাং, (x, y) = (m₁x₂ - m₂x₁ / m₁ - m₂, m₁y₂ - m₂y₁ / m₁ - m₂)",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q8.png'),},

"l0c303q9": {
	rightno: option4,
		question: "যদি (x₁, y₁) (x₂, y₂), (x₃, y₃) বিন্দুগুলো একটি ত্রিভুজের ভরকেন্দ্রের স্থানাঙ্ক হয়, তাহলে (x, y) = ?",
			attribute: "",
				op1: "(x, y) = ( x₁² + x₂² + x₃² / 9,  y₁² + y₂² + y₃² / 9)",
					op2: "(x, y) = ( x₁ - x₂ - x₃ / 3,  y₁ - y₂ - y₃ / 3 )",
						op3: "(x, y) = ( x₁ + x₂ + x / 3,  y₁ + y₂ + y / 3 )",
							op4: "(x, y) = ( x₁ + x₂ + x₃ / 3,  y₁ + y₂ + y₃ / 3 ) ",
								proof: "\n\n এখানে, BC এর মধ্যবিন্দুর স্থানাঙ্ক D হলো (x₂ + x₂ / 2, y₂ + y₃ / 2) \n\n মনে করি, G (x, y) এবং G বিন্দুর স্থানাঙ্ক 2: 1 অনুপাতে AD AD কে ছেদ করে। \n\n অতএব, AG : GD = 2 : 1 \n\n , x = { 2 . (x₂ + x₃ / 2) + 1 . x₁ } / 2 + 1 \n\n = x₁ + x₂ + x₃ / 3  \n\n এবং, y = { 2 . (y₂ + y₃ / 2) + 1 . y₁ } / 2 + 1 \n\n = y₁ + y₂ + y₃ / 3 \n\n সুতরাং, ভরকেন্দ্র (x, y) = ( x₁ + x₂ + x₃ / 3,  y₁ + y₂ + y₃ / 3 )",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q9.png'),},

"l0c303q10": {
	rightno: option1,
		question: "মূলবিন্দুগামী কোনো সরলরেখার উপরস্থ কোনো বিন্দু (x₁, y₁) হলে, ঢাল m = ?",
			attribute: "",
				op1: "m = y₁ / x₁",
					op2: "m = y - y₁ / x - x₁",
						op3: "m =  y / x",
							op4: "m = - y₁ / x₁",
								proof: "নাই",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q11": {
	rightno: option2,
		question: "x অক্ষের সমান্তরাল সরলরেখার সমীকরণ, y = ?",
			attribute: "",
				op1: "y = 1",
					op2: "y = b",
						op3: "y = a",
							op4: "y = 0",
								proof: "\n\n বিঃ দ্রঃ যেহেতু x অক্ষের সমান্তরাল বলা হয়েছে তাই y = b. যদি বলত, x অক্ষের সমীকরণ বা b = 0 তাহলে, y = 0 হত।",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q12": {
	rightno: option4,
		question: "y অক্ষের সমান্তরাল সরলরেখার সমীকরণ, x = ?",
			attribute: "",
				op1: "x = 0",
					op2: "x = 1",
						op3: "x = a",
							op4: "x = a",
								proof: "\n\n যেহেতু y অক্ষের সমান্তরাল বলা হয়েছে তাই x = a. যদি বলত, x অক্ষের সমীকরণ বা a = 0 তাহলে, y = 0 হত।",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q13": {
	rightno: option1,
		question: "মূলবিন্দুগামী সরলরেখার সমীকরণ, y = ?",
			attribute: "",
				op1: "y = mx",
					op2: "y = mx + c",
						op3: "y = 0",
							op4: "y = b",
								proof: "\n\n মূলবিন্দুগামী (0, 0) হওয়ায় tanθ = y / x \n\n বা, m = y / x... ..  [m = tanθ] \n\n বা, y = mx",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q14": {
	rightno: option3,
		question: "নির্দিষ্ট বিন্দুর সরলরেখার সমীকরণ, y = ?",
			attribute: "",
				op1: "y = b",
					op2: "y = mx ",
						op3: "y = mx + c",
							op4: "y = 0",
								proof: "",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q15": {
	rightno: option2,
		question: "দুইটি বিন্দু দিয়ে গমনকারী (কোনো অক্ষরেখার সমান্তরাল নয়) সরলরেখার সমীকরণ নিচের কোনটি?",
			attribute: "",
				op1: "m = y / x",
					op2: "x - x₁ / x₁ - x ₂ = y - y₁ / y₁ - y₂",
						op3: "y =  (y₁ / x₁) m",
							op4: "x/a  + y/b = 1",
								proof: "\n\n মনে করি, বিন্দু দুইটির স্থানাংক (x₁, y₁) ও x₂, y₂) \n\n এখানে, x₂ ≠ x₁ এবং y₂ ≠ y₁ \n\n ঢাল m এবং (x₁, y₁) বিন্দুগামী সরলরেখার সমীকরণ, y - y₁ = m (x - x₁)... ...(ii) \n\n যেহেতু, (ii) নং রেখাটি (x₂, y₂) দিয়ে যায়, \n\n অতএব, y₂ - y₁ = m (x₂ - x₁) \n\n সুতরাং, m = y₂ - y₁ / x₂ - x₁... ... (iii) \n\n (ii) নং সমীকরণে m এর মান প্রতিস্থাপন করে পাই, \n\n y - y₁ = (y₂ - y₁ / x₂ - x₁) (x - x₁)......(iv) \n\n বা, y - y₁ / y₂ - y₁ = x - x₁ / x₂ - x₁ \n\n তাই, \n\n x - x₁ / x₁ - x ₂ = y - y₁ / y₁ - y₂",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q15.png'),},

"l0c303q16": {
	rightno: option3,
		question: "উভয় অক্ষকে ছেদকৃত সরলরেখার সমীকরণ কোনটি?",
			attribute: "",
				op1: "x/a + y/b = - 1",
					op2: "x/a + y/b = 0",
						op3: "x/a + y/b = 1",
							op4: "x/a - y/b = -1",
								proof: "\n\n মনে করি, AB সরলরেখার উপর অবস্থিত বিন্দুসমূহের সেটের P(x, y) যে কোনো একটি উপাদান। এখন P বিন্দু হতে x অক্ষ এবং y অক্ষের উপর যথাক্রমে PM ও PN লম্ব অঙ্কন করি এবং O, P যোগ করি। \n\n ꕔOAB = ꕔOAP + ꕔOBP \n\n তাই, 1/2 OA.OB = 1/2 OA.PM + 1/2 OB.PN \n\n বা, 1/2 a.b = 1/2 a.y + 1/2 b.x \n\n উভয় পক্ষকে 1/2 ab দ্বারা ভাগ করে পাই, 1 = y/b + x/a \n\n সুতরাং, x/a + y/b = 1 \n\n বিকল্পঃ x অক্ষের উপর A(a, 0) এবং y অক্ষের উপর B(0, b) বিন্দুদ্বয় দিয়ে গমনকারী সরলরেখার সমীকরণ, \n\n x - a / a - 0 = y - 0 / 0 - b \n\n বা, - bx + ab = ay \n\n বা, bx + ay = ab \n\n বা, x/a + y/b = 1",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q16.png'),},

"l0c303q17": {
	rightno: option1,
		question: "সরলরেখার সমীকরণ নির্ণয়ঃ ",
			attribute: "যা x অক্ষের ধনাত্নক দিকের সাথে θ কোণ উৎপন্ন করে এবং একটি নির্দিষ্ট বিন্দু দিয়ে যায়।",
				op1: "x - x₁ / cosθ = y - y₁ / sinθ = r",
					op2: "x₁ - y₁ / x - y = rtanθ",
						op3: "x - x₁ / y - y₁  = rtanθ",
							op4: "x + x₁ / cosθ = y + y₁ / sinθ = r",
								proof: "\n\n মনে করি, LM সরলরেখা x অক্ষের সাথে θ কোণ উৎপন্ন করে। \n\n সুতরাং, \u2220 MLX = \u2220 PQT = \n\n কিন্তু, QT = SR = OR - OS = x - x7 \n\n PT = PR - TR = PR - QS = y - y₁ \n\n এবং PQ = r \n\n এখন, সমকোণী PQT ত্রিভুজ হতে পাই, \n\n QT / PQ = cosθ \n\n  QT = PQ cosθ \n\n সুতরাং, x - x₁ = rcosθ \n\n আবার, PT / PQ = sinθ \n\n PT = PQ sinθ \n\n  সুতরাং, y - y₁ = r sinθ \n\n অতএব, \n\n x - x₁ / cosθ = y - y₁ / sinθ = r",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q18": {
	rightno: option4,
		question: "দুইটি অসমান্তরাল রেখার মধ্যবর্তী কোণ, tanθ = ?",
			attribute: "",
				op1: "tanθ =  ax / by",
					op2: "tanθ = ± 1 + m₁m₂ / m₁ - m₂",
						op3: "tanθ = y / x",
							op4: "tanθ = ± m₁ - m₂ / 1 + m₁m₂",
								proof: "\n\n মনে করি, AB ও AC সরলরেখা দুইটির অন্তর্ভুক্ত কোণ θ ; তাহলে, ∠BAC = θ. \n\n মনে করি, ∠ABX = θ₁ এবং ∠ACX = θ₂ এবং θ₁ > θ₂ \n\n সুতরাং, θ = θ₁ - θ₂..   (i) \n\n AB এবং AC সরলরেখার দুইটির সমীকরণ, y = m₁x + c₁ \n\n এবং, y = m₂x + c₂ \n\n তাহলে, tanθ₁ = m₁ এবং tanθ₂ = m₂ \n\n (i) নং থেকে পাই, tanθ = tan (θ₁ - θ₂) = tan θ₁ - tanθ₂ / 1 + tanθ₁ tanθ₂ \n\n অর্থ্যাৎ, tanθ = m₁ - m₂ / 1 + m₁m₂ \n\n θ₂ > θ₁ হলে, θ = θ₂ - θ₁ = - (θ₁ - θ₂) \n\n তাই, tanθ = tan { - (θ₁ - θ₂)} = - tan (θ₁ - θ₂) = - tanθ₁ - tanθ₂ / 1 + tanθ₁ tanθ₂ = - m₁ - m₂ / 1 + m₁m₂ \n\n সুতরাং, tanθ = ± m₁ - m₂ / 1 + m₁m₂",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q19": {
	rightno: option3,
		question: "m₁ ও m₂ ঢালবিশিষ্ট দুইটি সরলরেখা পরষ্পর সমান্তরাল হলে নিচের কোনটি সঠিক?",
			attribute: "",
				op1: "m₁ > m₂",
					op2: "m₁ ≠ m₂",
						op3: "m₁ = m₂",
							op4: "m₂ > m₁",
								proof: "নাই",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q20": {
	rightno: option4,
		question: "দুইটি সরলরেখা পরষ্পর সমান্তরাল হওয়ার শর্ত?",
			attribute: "রেখাদ্বয় যথাক্রমেঃ a₁x + b₁y + c₁ = 0 \n a₂x + b₂y + c₂ = 0",
				op1: "a₁ - b₁ = a₂ - b₂",
					op2: "a₁a₂ = b₁b₂",
						op3: "a₁ - a₂ = b₁ - b₂",
							op4: "a₁ / a₂ = b₁ / b₂",
								proof: "\n\n y =  m₁x + c₁ \n\n এবং y = m₂x + c₂ রেখা দুইটি সমান্তরাল হওয়ার শর্ত θ₁ = θ₂ \n\n tanθ₁ = tanθ₂ \n\n বা, m₁ = m₂ \n\n অনুরুপভাবে, a₁x + b₁y + c₁ = 0 \n\n এবং a₂x + b₂y + c₂ = 0 রেখা দুইটির সমান্তরাল হওয়ার শর্ত হলো - a₁/b₁ = - a₂/b₂ \n\n বা, a₁/a₂ = b₁/b₂",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q20.png'),},

"l0c303q21": {
	rightno: option3,
		question: "m₁ ও m₂ ঢালবিশিষ্ট দুইটি সরলরেখা পরস্পর লম্ব হলে, m₁m₂ = ?",
			attribute: "",
				op1: "m₁m₂ = ± 1",
					op2: "m₁m₂ = 1",
						op3: "m₁m₂ = -1",
							op4: "m₁m₂ = 0",
								proof: "\n\n দুইটি সরলরেখা পরস্পর লম্ব হওয়ার শর্ত হচ্ছে, এদের অন্তর্ভুক্ত কোণ সমকোণ হওয়া অর্থাৎ θ₂ = θ₁ + 90° অথবা θ₁= θ₂ + 90°, যখন (যথাক্রমে) θ₂ > θ₁ বা θ₁ > θ₂।  এখন, m₂ = tanθ₂ = tan(θ₁ + 90°) = - cotθ₁ = - 1/m₁ \n\n অথবা, m₁ = tanθ₁ = tan(θ₂ + 90°) = - cotθ₂ = - 1/m₂ হবে। \n\n অর্থাৎ, m₁m₂ = - 1",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q22": {
	rightno: option1,
		question: "দুইটি সরলরেখার লম্ব হওয়ার শর্ত?",
			attribute: "",
				op1: "a₁a₂ + b₁b₂ = 0 ",
					op2: "a₁a₂ + b₁b₂ = 1",
						op3: "a₁a₂ + b₁b₂ = -1",
							op4: "a₁a₂ + b₁b₂ = -1/m",
								proof: "নাই",
									pic: "",
										picon: false,
											picproof: "",},

"l0c303q23": {
	rightno: option3,
		question: "ত্রিভুজের ভরকেন্দ্রের স্থানাঙ্কের সূত্র কোনটি?",
			attribute: "",
				op1: "ত্রিভুজের ভরকেন্দ্রের স্থানাঙ্ক = ( ( x¹+ x²+ x³)/2 ) , (y¹+ y²+ y³)/2) )",
					op2: "ত্রিভুজের ভরকেন্দ্রের স্থানাঙ্ক = ( ( x¹+ x²+ x³)/1 ) , (y¹+ y²+ y³)/3) )",
						op3: "ত্রিভুজের ভরকেন্দ্রের স্থানাঙ্ক = ( ( x¹+ x²+ x³)/3 ) , (y¹+ y²+ y³)/3) )",
							op4: "ত্রিভুজের ভরকেন্দ্রের স্থানাঙ্ক = ( ( x¹+ x²+ x³)/2 ) , (y¹+ y²+ y³)/3) )",
								proof: "\n\n মনে করি, ABC ত্রিভুজের শীর্বত্রয় A (x₁ , y₁) , B (x₂ , y₂) এবং C (x₃ y₃) ; BC , CA এবং AB বাহুর মধ্যবিন্দু যথাক্রমে D , E , F. এখন AD , BE , CF মধ্যমাত্রয় অঙ্কন করলে তারা পরস্পর G বিন্দুতে ছেদ করবে । G বিন্দুটিকে ত্রিভুজের ভরকেন্দ্র বলা হয় এবং তা প্রত্যেক মধ্যমাকে 2 : 1 অনুপাতে অন্তর্বিভক্ত করে । এখন BC এর মধ্যবিন্দু D এর স্থানাংক ((x₂ + x₃)/2, (y₂ + y₃)/2) \n\n ধরি, G এর স্থানাংক (x, y), ∵ AG : GD = 2 : 1 \n\n ∴ x = 2 . (x₂ + x₃)/2 + 1 . (x₁)/(2 + 1) =  (x₁ + x₂ + x₃)/3 \n\n এবং, y = 2 . (y₂ + y₃)/2 + 1 . (y₁)/(2 + 1) = (y₁ + y₂ + y₃)/3 \n\n সুতরাং , ABC এর ভরকেন্দ্র = ( ( x¹ + x² + x³)/(3) ) , ((x¹ + x² + y³)/3)",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q23.png'),},

"l0c303q24": {
	rightno: option1,
		question: "A(x₁, y₁), B(x₂, y₂) and C(x₃ , y₃) area of a triangle formed by the three points, ΔABC = ?",
			attribute: "",
				op1: "ΔABC  =1/2 \n{|x¹ y¹| + |x² y²|  + |x³ y³| \n |x² y²| + |x³ y³| + |x¹ y¹|}",
					op2: "ΔABC  =2 \n{|x¹ y¹| + |x² y²|  + |x³ y³| \n |x² y²| + |x³ y³| + |x¹ y¹|}",
						op3: "ΔABC  =\n{|x¹ y¹| + |x² y²|  + |x³ y³| \n |x² y²| + |x³ y³| + |x¹ y¹|}",
							op4: "ΔABC  =1/2 \n{|x² y²| + |x³ y³| + |x¹ y¹|\n |x¹ y¹| + |x² y²| + |x³ y³|}",
								proof: "\n\n মনে করি , ΔABC এর শীর্ষবিন্দুগুলি A(x₁, y₁), B (x₂, y₂), C (x₃, y₃). \n\n A, B, C বিন্দু থেকে x- অক্ষের উপর যথাক্রমে AM, BL, CN লম্ব আঁকি। তাহলে, LM = OM - OL = x₃ - x₂ \n\n LM = OM - OL = x₁ - x₂ এবং MN = ON - OM \n\n = x₃ - x₁ \n\n ∴ ΔABC এর ক্ষেত্রফল = ট্রাপিজিয়াম ABLM এর ক্ষেত্রফল + ট্রাপিজিয়াম AMNC এর ক্ষেত্রফল - ট্রাপিজিয়াম BLNC এর ক্ষেত্রফল \n\n = 1/2 (AM + BL) . LM + 1/2 (AM + CN) . MN - 1/2 (BL + CN) . LN \n\n = 1/2  {(y₁ + y₂) (x₁ - x₂) (y₁ + y₃) (x₃ - x₁) - (y₂ + y₃) (x₃ - x₂)} \n\n = 1/2  {x₁ (y₁ + y₂ - y₁ - y₃) + x₂ (y₂ + y₃ - y₁ - y₂) + x₃(y₁ + y₃ - y₂ - y₃)} \n\n ∴ ΔABC এর ক্ষেত্রফল = 1/2  {x₁(y₂ - y₃) + x₂ (y₃ - y₁) + x₃(y₁ - y₂)} \n\n ΔABC  =1/2 \n{|x¹ y¹| + |x² y²|  + |x³ y³| \n |x² y²| + |x³ y³| + |x¹ y¹|}",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q24.png'),},

"l0c303q25": {
	rightno: option4,
		question: "(x₁ , y₁) এবং (x₂ , y₂) বিন্দুগুলোর সংযোগকারী ঢাল, m = ?",
			attribute: "",
				op1: "m = (y₁ - y₂)/(x₂  – x₁)",
					op2: "m = (x₁ - x₂)/(y₁ - y₂)",
						op3: "m = (y - y₂)/(x - x₂) × (y₁ - y₂)/(x₁ - x₂)",
							op4: "m = (y₁ - y₂)/(x₁ - x₂)",
								proof: "\n\n মনে করি, AB সরলরেখাটি দুইটি নির্দিষ্ট বিন্দু P (x₁ , y₁) I Q (x₂ , y₂)  দিয়ে যায় এবং তা x- অক্ষের ধনাত্মক দিকের সাথে Ø কোণ উৎপন্ন করে । P ও Q বিন্দু থেকে x- অক্ষের উপর যথাক্রমে PM  ⊥ QN  লম্ব টানি। \n\n QR ⊥ PM এবং ∠QAN = Ø = \u2220 PQR      [ অনুরূপ কোণ] \n\n এখন, PR = PM - RM = y₁ - y₂ এবং \n\n QR = NM = OM - ON = x₁ - x₂ \n\n ∴ AB রেখার ঢাল, m = tan Ø = PR/QR = (y₁ - y₂)/(x₁ - x₂)",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q25.png'),},

"l0c303q26": {
	rightno: option1,
		question: "ax + by + c₁ = 0, ax + by + c₂ = 0 হলে, d = ?",
			attribute: "d = দুইটি সমান্তরাল রেখার মধ্যবর্তী দূরত্ব",
				op1: "d = |(c₁ - c₂ )/( √(a² + b²)) |",
					op2: "d = |(c₂  – c1 )/( √(a² + b²)) |",
						op3: "d = |( √(a² + b²)  )/(c₁ - c₂) |",
							op4: "d = |(c₁+ c₂ )/( √(a² + b²)) |",
								proof: "\n\n প্রদত্ত সমীকরণদ্বয়: ax + by + c₁ = 0 ... (i)  \n\n   ax + by + c₂ = 0 ... (ii) \n\n মূলবিন্দু 0(0, 0) থেকে (i) রেখার দূরত্ব ON = a . 0 + b . 0 + (c₁)/√(a² + b²) = (c₁)/√(a² + b²) \n\n ∴ সমান্তরাল রেখা দুইটির মধ্যবর্তী দূরত্ব, MN = ON - OM = d = | (c₁ - c₂ )/( √(a² + b²)) |",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q26.png'),},

"l0c303q27": {
	rightno: option2,
		question: "(x₁, y₁) বিন্দু হতে ax + by + c = 0 রেখার লম্ব দৈর্ঘ্য, V = ?",
			attribute: "V = লম্ব",
				op1: "V = | (ax + by + c)/√(a² + b²)  |",
					op2: "V = | (ax₁ + by₁ + c)/√(a² + b²)  |",
						op3: "V = | (ax₁ + by₁ + c)/√(a^2  - b²)  |",
							op4: "V = | (ax₁ + by₁ )/√(a² + b²)  |",
								proof: "\n\n P (x₁ y₁) বিন্দু হতে ax + by + c = 0 সরলরেখার উপর অংকিত লম্বের দৈর্ঘ্য নির্ণয় করতে হবে। মনে করি, ax + by + c = 0 রেখাটি x I y- অক্ষকে যথাক্রমে A ও B বিন্দুতে ছেদ করে । প্রদত্ত সমীকরণকে নিম্নরূপে লেখা যায়: \n\n x/(-cla) + y/clb = 1 = OA = - cla, and OB = - clb. \n\n ∴ AB² = OA² + OB² = c²/a² + c²/b²  \n\n ∴ AB = ± c/(ab√(a² + b²)) \n\n P (x₁ y₁) বিন্দু থেকে যথাক্রমে x এবং y অক্ষের উপর PM ⊥ PN লম্ব আঁকি। সুতরাং, PM = y₁, PN =  x₁ \n\n ধরি, P থেকে AB রেখার উপর অঙ্কিত লম্ব দৈর্ঘ্য PR = d. \n\n এখন, ΔOAB = ΔOAP + ΔOBP + ΔABP \n\n বা, 1/2 (-c/a) (-c/b) = 1/2 (-c/a). y₁ + 1/2 (-c/b) x₁ + 1/2  d × AB \n\n বা, ± d × c/(ab√(a² + b²))  = (cx₁)/b + (cy₁)/a + c²/ab \n\n = ± d × √(a² + b²)  = ax₁ + by₁ + c, [ab/c দ্বারা গুণ করে] \n\n সুতরাং, d = ± ax₁ + by₁ + c/√(a² + b²) \n\n ∴ P (x₁ y₁) বিন্দু হতে ax + by + c = 0 রেখার লম্ব দৈর্ঘ্য, V = | (ax₁ + by₁ + c)/√(a² + b²) |",
									pic: "",
										picon: false,
											picproof: require('../assets/l0c303q27.png'),},

"l0c303q28": { },

