//l1c305
 "l1c305q1":{
                rightno: option3, 
                question: "If all things are different, ⁿPᵣ=?", 
                attribute:"", 
                op1:"ⁿPᵣ= n!/(n-r)",   
                op2:"ⁿPᵣ= n/(n-r)", 
                op3:"ⁿPᵣ=  n!/(n-r)!", 
                op4:"ⁿPᵣ= n!/(r-n)!", 
                proof:"\n\n We know,\n\n ⁿPᵣ =n(n-1)(n-2) ... (n-r+1) \n\n = (n(n-1)(n-2)… (n-r+1)(n-r)(n-r-1)… 3.2.1.)/((n-r)(n-r-1)… 3.2.1) \n\n  = n!/(n-r)!", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c305q2":{
                rightno: option1, 
                question: "If all things are different, ⁿPₙ=? [Where, n∈ N  r ≤ n]", 
                attribute:"", 
                op1:"ⁿPₙ = n!",  
                op2:"ⁿPₙ = n! (n-r)!", 
                op3:"ⁿPₙ = n!/(n-r)", 
                op4:"ⁿPₙ = n(n-r)!", 
                proof:"\n\n n is the number of formats, taking all things together from a number of different things. \n\n ⁿPₙ =n(n-1)(n-2) ... Up to n number of producers  \n\n =n(n-1(n-2) ... (n-n+1)=n(n-1)(n-2) ... 1 = n(n-1)(n-2) ... 3.2.1. \n\n  ∴ⁿPₙ =n!", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c305q3":{
                rightno: option4, 
                question: "At Determinant, n! = ?", 
                attribute:"", 
                op1:"n! = n/((n-1)! ) =  n/((n-1)(n-2)! )",  
                op2:"n! = (n-1)! = (n-1)(n-2)! Etc.", 
                op3:"n! = n(n-1)! = n(n-1)(n-2)!  Etc.", 
                op4:"n! = n(n-1)! = n(n-1)(n-2)! Etc.", 
                proof:"\n\n The consecutive product of all normal numbers from 1 to n is usually n! Is expressed by n! = n(n-1)(n-2)(n-3)... 3.2.1 = n(n-1)! \n\n =n(n-1)(n-2)!=n(n-1)(n-2)....(n-r=1)(n-r)! \n\n Such as, 6! = 6.5.4.3.2.1 \n\n =6.5!=6.5.4!", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c305q4":{
                rightno: option2, 
                question: "In the case where not all are different, the format number is taken together as X = ?", 
                attribute:"", 
                op1:"X = n/pqr!",  
                op2:"X = n!/p!q!r!", 
                op3:"X = n/pqr", 
                op4:"X = n! (p!q!r!)", 
                proof:"\n\n Suppose, among the number of n things, p number is one type, q number is second type, r number is third type and the rest of the things are different.\n\n If p is replaced by the same number of identical things as p, then these individual things are replaced by p! Can be sorted in a number of ways. That is, the diagnostic format is from one to p! Number of formats available. Now if the number to be determined is x, holding the number p separately will make the total number of formats x × p! \n\n Similarly x × p! If each q of the same format is replaced by the same number of individual items, the total format number will be x × p! × q! \n\n Similarly x × p! × q! × r! The total number of layouts is x × p! × q! × r! \n\n Now everything is unique. So, all of the n number things will be absolutely the format number n! \n\n ∴ x × p! × q! × r! = n! thereby, x= n!/p!q!r! \n\n ∴ x = n!/p!q!r!", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c305q5":{
                rightno: option1, 
                question: "ⁿCᵣ = ? ", 
                attribute:"", 
                op1:"ⁿCᵣ = n!/r!(n-r)!",  
                op2:"ⁿCᵣ = n!/(n-r)!", 
                op3:"ⁿCᵣ = n!r!(n-r)!", 
                op4:"ⁿCᵣ = n!r!/(n-r)!", 
                proof:"\n\n The number of nCr assemblies in which a will always be a is n-1Cr-1 , because in each of the n-1Cr-1 assemblies with a (r-1) number of letters from each of the remaining (n-1) letters except a If included, the total number of characters in that assembly will be r. \n\n Similarly, all the assemblies that have b, c, d ... will have n-1Cr-1 So, if all the assemblies are written with the r number every time from n different letters, then each letter will have ⁿ⁻¹C ᵣ₋₁ number in those assemblies.\n\n Since the total number of letters is n therefore the number of letters in the written assemblies = n × ⁿ⁻¹C ᵣ₋₁ ... (i) \n\n Again each assembly has the number of r so the total number of letters in the assembly, nCr =  r × ⁿCᵣ ... (ii) \n\n So, from (i) I (ii)  r× ⁿCᵣ = n × ⁿ⁻¹Cᵣ₋₁  \n\n ∴ ⁿCᵣ = n/r × ⁿ⁻¹C ᵣ₋₁ ... (1) \n\n Similarly, ⁿ⁻¹C ᵣ₋₁  = n-1/r-1 × ⁿ⁻²C ᵣ₋₂ ... (2) \n\n ⁿ⁻²C ᵣ₋₂ = n-2/r-2 × ⁿ⁻³C ᵣ₋₃ ... (3) \n\n ............................................................................. \n\n ⁿ⁻ʳ⁺²C₂ = n-r+2/2 × ⁿ⁻ʳ⁺¹C₁ ... (n) \n\n By multiplying all from (1) to (n) together and subtracting the common product from both sides of the product we get, \n\n ⁿCᵣ= n(n-1)(n-2)....(n-r+2)/r(r-1)(r-2).....2 × ⁿ⁻ʳ⁺¹Cᵣ  \n\n Now ⁿ⁻ʳ⁺¹C₁ means (n - r + 1) the number of assemblies by taking 1 from each number of things. Thus, ⁿ⁻ʳ⁺¹C₁ = n-r + 1 \n\n ∴ⁿCᵣ = n(n-1)(n-2)...(n-r+2)(n-r+1)/r! \n\n =(n(n-1)(n-2)….(n-r+2)(n-r+1)(n-r)!)/r!(n-r)! \n\n =n!/r!(n-r)!", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c305q6":{
                rightno: option2, 
                question: "In supplementary assembly, ⁿCᵣ = ?", 
                attribute:"", 
                op1:"ⁿCᵣ = ⁿCₙ - rCr",  
                op2:"ⁿCᵣ = ⁿCₙ₋ᵣ ", 
                op3:"ⁿCᵣ = rCr - ⁿCₙ", 
                op4:"ⁿCᵣ = nCr-n", 
                proof:"\n\n We know, ⁿCᵣ = n!/r!(n-r)!  and ⁿCₙ₋ᵣ = n!/(n-r)!(n-n+r)! = n!/(n-r)!r! \n\n In general, ⁿCᵣ and ⁿCₙ₋ᵣ complement each other. \n\n ∴ⁿCᵣ = ⁿCₙ₋ᵣ", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c305q7":{
                rightno: option2, 
                question: "In supplementary assembly,  ⁿ⁺¹Cᵣ = ?", 
                attribute:"", 
                op1:"ⁿ⁺¹Cᵣ = ⁿCᵣ  -  ⁿCᵣ₋₁",  
                op2:"ⁿ⁺¹Cᵣ = ⁿCᵣ + ⁿCᵣ₋₁", 
                op3:"ⁿ⁺¹Cᵣ = ⁿCᵣ - 1 - ⁿCᵣ", 
                op4:"ⁿ⁺¹Cᵣ = ⁿCn  + ʳCᵣ", 
                proof:"\n\n ⁿCᵣ + ⁿCᵣ₋₁ = n!/r!(n-r)! + n!/(r-1)(n-r+1)! \n\n =(n!/r.(r-1)!(n-r)!+n!)/((r-1)!(n-r+1).(n-r)!) \n\n =n!/(r-1)!(n-r)!  {(1/r+1)/(n-r+1) } = n!/(r-1)1(n-r)! . (n+1)/r(n-r+1) \n\n =(n+1)!/(n-r+1)!r! = (n+1)!/r!{(n+1)-r}! = n+¹Cᵣ", 
                pic: "", 
                picon: false ,
                picproof: "",},

              "l1c305q8":{},
