//Chapter 2 - Vector 

 "l1c302q1":{
                rightno: option3, 
                question: "Which is the exchange rule for vector addition?", 
                attribute:"P\u0305, Q\u0305, R\u0305 are the vector sign and m and n are two scaler sign", 
                op1:"m(P+Q) = mP + mQ",   
                op2:"(P + Q) + R = P + (Q + R)", 
                op3:"P + Q = Q + P", 
                op4:"mP = Pm", 
                proof:"\n\n (P + Q) + R = P + (Q + R)  is the rule of co-provision \n\n m(P+Q) = mP + mQ         is the distribution rules for scaler multiplication \n\n mP = Pm 	is the exchange rules for scaler multipliers \n\n So,   P + Q = Q + P	is  the exchange rule for vector addition", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c302q2":{
                rightno: option2, 
                question: "What is the rule of co-provision of vectors ?", 
                attribute:"P\u0305, Q\u0305, R\u0305 are the vector sign and m and n are two scaler sign", 
                op1:"P\u0305 + Q\u0305 = Q\u0305 + P\u0305",  
                op2:"(P\u0305 + Q\u0305) + R\u0305 = P\u0305 + (Q\u0305 + R\u0305)", 
                op3:"mP\u0305 = P\u0305m", 
                op4:"(m + n) P\u0305 = mP\u0305 + nP\u0305", 
                proof:"\n\n P\u0305 + Q\u0305 = Q\u0305 + P\u0305	is the exchange rule for vector addition \n\n mP\u0305 = P\u0305m 	is the exchange rules for scaler multipliers \n\n (m + n) P\u0305 = mP\u0305 + nP\u0305 is the distribution rules for scaler multiplication \n\n So, 		(P\u0305 + Q\u0305) + R\u0305 = P\u0305 + (Q\u0305 + R\u0305) 	is the rule of co-provision of vectors", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c302q3":{
                rightno: option4, 
                question: "	What rule is for mP\u0305 = P\u0305m vector?", 
                attribute:"P\u0305, Q\u0305, R\u0305 are the vector sign and m and n are two scaler sign", 
                op1:"Co-provision rules",  
                op2:"Co-provision rules of scaler multiplier", 
                op3:"Distribution rules for scaler multiplication", 
                op4:"Exchange Rules for Scaler Multiples", 
                proof:"\n\n mP\u0305 = P\u0305m   is the exchange rules for scaler multipliers", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c302q4":{
                rightno: option1, 
                question: "	What rule is for m(nP\u0305) = mnP\u0305 vector?", 
                attribute:"P\u0305, Q\u0305, R\u0305 are the vector sign and m and n are two scaler sign", 
                op1:"Co-provision rules for Scaler Multiples",  
                op2:"Exchange Rules for Scaler Multiples", 
                op3:"Co-provision rules", 
                op4:"Distribution rules for scaler multiplication", 
                proof:"\n\n m(nP\u0305) = mnP\u0305 is the co-provision rule of the scaler multiples", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c302q5":{
                rightno: option1, 
                question: "Which is the distribution rule for the scaler multiplication of vectors? ", 
                attribute:"P\u0305, Q\u0305, R\u0305 are the vector sign and m and n are two scaler sign", 
                op1:"(m + n) P\u0305 = mP\u0305 + nP\u0305",  
                op2:"mP\u0305 = P\u0305m", 
                op3:"(P\u0305 + Q\u0305) + R\u0305 = P\u0305 + (Q\u0305 + R\u0305)", 
                op4:"m(P\u0305+Q\u0305) = mP\u0305 - mQ\u0305", 
                proof:"\n\n mP\u0305 = P\u0305m is the exchange rules for scaler multipliers \n\n (P\u0305 + Q\u0305) + R\u0305 = P\u0305 + (Q\u0305 + R\u0305)  is the rule of co-provision of vectors. \n\n m(P\u0305+Q\u0305) = mP\u0305 - mQ\u0305    No rules \n\n So, 		(m + n) P\u0305 = mP\u0305 + nP\u0305 is the distribution rule for the scaler multiplication of vectors.", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c302q6":{
                rightno: option4, 
                question: "Which is the distribution rule for scaler multiplication?", 
                attribute:"P\u0305, Q\u0305, R\u0305 are the vector sign and m and n are two scaler sign", 
                op1:"mP\u0305 = P\u0305m",  
                op2:"m(P\u0305+Q\u0305) = mP\u0305 – mQ\u0305", 
                op3:"(m- n) P\u0305 = mP\u0305 – nP\u0305", 
                op4:"m(P\u0305+Q\u0305) = mP\u0305 + mQ\u0305", 
                proof:"\n\n m(P\u0305+Q\u0305) = mP\u0305 – mQ\u0305  No rules  \n\n (m- n) P\u0305 = mP\u0305 – nP\u0305	 No rules \n\n mP\u0305 = P\u0305m 		is the exchange rules for scaler multipliers \n\n So, m(P\u0305+Q\u0305) = mP\u0305 + mQ\u0305 	is the distribution rule for scaler multiplication", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c302q7":{
                rightno: option2, 
                question: "If P point is the middle point of AB then P’s position vector, r\u0305 = ?", 
                attribute:"P = Middle point, m = n, a\u0305 = position vector, b\u0305 = position vector, AB = line \n Press question for detailed image", 
                op1:"r = 2(a+b)",  
                op2:"r =  1/2  (a+b)", 
                op3:"r = (m (a-b))/2m", 
                op4:"r = 2/(a + b)", 
                proof:"\n\n If P point is the middle point of AB then P’s position vector, \n\n r\u0305 = (m b + m a)/(m + m)	= (m(a+b))/(2m ) 	=  1/2  (a+b)", 
                pic: require('../assets/c302q7.png'), 
                picon: true ,
                picproof: "",},
              "l1c302q8":{
                rightno: option3, 
                question: "When point P divides AB into m∶ n ration, then r\u0305 = ?", 
                attribute:"P = Middle point, m = n, a\u0305 = position vector, b\u0305 = position vector, AB = line \n Press question for detailed image", 
                op1:"r = (m b + n a)/(m - n)",  
                op2:"r = (m b - n a)/(m + n)", 
                op3:"r = (m b – n a)/(m - n)", 
                op4:"r = (m b + n a)/(n - m)", 
                proof:"\n\n Defination", 
                pic: require('../assets/c302q7.png'), 
                picon: true ,
                picproof: "",},
              "l1c302q9":{
                rightno: option1, 
                question: "If point G divides AD inward into 2: 1 then G’s position vector, r\u0305 = ?", 
                attribute:"r\u0305 = Position Vector, AD = Median. Press question for detailed image", 
                op1:"r =  (a + b + c)/3",  
                op2:"r = (a²  + b²  + c²)/4", 
                op3:"r = ((a + b - c)²)/9 ", 
                op4:"r = ((a + b)  (b + c)  (c + a))/3", 
                proof:"\n\n Suppose, the position vector of the ABC triangle's vertex A,B,C is the middle point of BC,CA,AB respectively, three points a,b,c and D,E,F respectively. \n\n So, D's position vector 	(b + c)/2 \n\n E's position vector	 (c + a)/2 \n\n and    F's position vector 	(a + b)/2 \n\n If point G divides AD inward into 2: 1 then G’s position vector,  \n\n r\u0305 = (1a+2 ((b+c)/2))/(1+2) \n\n r\u0305 = (a + b + c)/3 ", 
                pic: require('../assets/c302q9.png'), 
                picon: true ,
                picproof: "",},
              "l1c302q10":{
                rightno: option2, 
                question: "r = ?", 
                attribute:"Press question for detailed image", 
                op1:"r = xk̂ + yĵ + zî",  
                op2:"r = xî + yĵ + zk̂", 
                op3:"r = xĵ + yî+ zk̂", 
                op4:"r = xî - yĵ - zk̂",  
                proof:"\n\n Suppose, OX,OY and OZ lines meet O points at right angle and indicate x,y,z axis respectively. \n\n Suppose, x,y,z a single vector towards the axis î,ĵ,k̂ and any point P respectively is the Cartesian coordinates of (x,y,z) \n\n Then, From the figure we get, OA = x, OB = y, OC = z \n\n Again, we know, \n\n  î = (OA\u0305/OA\u0305)  = (OA\u0305/x) \n\n or, OA\u0305  = xî \n\n Similarly OB\u0305  = y ĵ and OC\u0305 = z k \n\n Now, if length of OP  = r then, in ΔOPD , OP\u0305 = OD\u0305 + DP\u0305    … …(i) \n\n and, in ΔOBD , OD\u0305 = OB\u0305 + BD\u0305   … …(ii) \n\n Therefore, OP\u0305 = OD\u0305 + DP\u0305 = OB\u0305 + BD\u0305 + DP\u0305 \n\n = OB\u0305 + OA\u0305 + OC\u0305 \n\n  = OA\u0305 + OB\u0305  + OC\u0305 \n\n  So, r = x i + y j + z k", 
                pic: require('../assets/c302q10.png'), 
                picon: true ,
                picproof: "",},
              "l1c302q11":{
                rightno: option2, 
                question: "Vector equation of straight line, r = ?", 
                attribute:"λ = scaler, b = vector, a = vector \n Press question for detailed image", 
                op1:"r = a - λb",  
                op2:"r = a + λb", 
                op3:"r = b + λa", 
                op4:"r = (λa + λb)/ab", 
                proof:"\n\n Suppose, O is middle point and position vector of point A, OA\u0305 = a and P on the line is any point whose position vector OP\u0305 = r\u0305 \n\n From OAP triangle we get, OA\u0305   + AP\u0305  = OP\u0305 \n\n  or, AP\u0305  = OP\u0305  - OA\u0305 \n\n or, AP\u0305 = r – a… …(i) \n\n But AP\u0305 vector parallels b vector.So, AP\u0305  = λ b, when λ  is a scaler. \n\n From (i), AP\u0305 = r – a \n\n or,λ b = r – a  \n\n or, r = a + λb, which is the vector equation of the determining straight line.", 
                pic: require('../assets/c302q11.png'), 
                picon: true ,
                picproof: "",},
              "l1c302q12":{
                rightno: option4, 
                question: "The equation of the straight line to the main point(origin) and b vector, r = ?", 
                attribute:"λ = scaler, b = vector, a = vector \n Press question for detailed image", 
                op1:"r = λ a - λ b",  
                op2:"r = λ a", 
                op3:"r = a + λb", 
                op4:"r = λ b", 
                proof:"\n\n We know,  r = a + λb, which is the vector equation of the straight line. \n\n Now,	If the straight line is mainstream, then a = 0, so, the equation of the straight line parallel to the main point and b vector \n\n So, r = λ b", 
                pic: require('../assets/c302q11.png'), 
                picon: true ,
                picproof: "",},
              "l1c302q13":{
                rightno: option3, 
                question: "Vector equation of two dotted straight lines, r = ?", 
                attribute:"λ = scaler, b = vector, a = vector \n Press question for detailed image", 
                op1:"r = (1 - λ)b + λa",  
                op2:"r = (1+ λ)a- λb", 
                op3:"r = (1 - λ)a + λb", 
                op4:"r = (1+ λ)b + λa", 
                proof:"\n\n Suppose, O is middle point, the line passes through A and B point and P is any point on the line. \n\n Suppose, position vector of A,B and P points is respectively OA\u0305 = a, OB\u0305 = b and OP\u0305 = r\u0305 \n\n From the figure we get, 	OA\u0305  + AB\u0305  = OB\u0305 \n\n or, AB\u0305  = OB\u0305  – OA\u0305  = (b – a) \n\n Now, the container line of the AP\u0305  and AB\u0305 vectors is the same. So, \n\n AP\u0305  = λ AB\u0305 \n\n AP\u0305 = λ (b – a) \n\n again, OA\u0305  + AP\u0305 = OP\u0305		or, AP\u0305  = OP\u0305  – OA\u0305	or, λ(b – a) = r – a \n\n Therefore, 	  r = (1 - λ)a + λb , which is the vector equation of two dotted straight lines.", 
                pic: require('../assets/c302q13.png'), 
                picon: true ,
                picproof: "",},
              "l1c302q14":{
                rightno: option1, 
                question: "How many times the cross product value of the two vectors is of the respective parallelogram’s area?", 
                attribute:"Press question for detailed image", 
                op1:"Equal",  
                op2:"Double", 
                op3:"Triple", 
                op4:"Four times", 
                proof:"\n\n From OACB parallel, two vectors a and b are indicated by two adjacent arms of the OA and OB respectively. \n\n If ∠AOB = 0 , then \n\n a × b = OA\u0305  × OB\u0305   = | OA\u0305 |  | OB\u0305 |  sin θ n̂  \n\n Where a single vector perpendicular to the plane surface of the vectors a and b. Mention: If the right-arm scroll from a to b is rotated at the smallest angle, the direction of the n̂  is along the OD and the direction of the n̂  will be along the DO if it rotates from b to a. \n\n  Again, |c| =  |a × b| = (OA) (OB) sin θ \n\n |c| = (OA) h, when h = OB sin θ \n\n = 2. 1/2 OA.h \n\n = 2 × ΔOAB \n\n = The area of OACB parallel \n\n So, the cross product value of the two vectors is equal to the area of the respective parallel.", 
                pic: require('../assets/c302q14.png'), 
                picon: true ,
                picproof: "",},  
              "l1c302q15":{
                rightno: option4, 
                question: "What are the conditions for two parallel vectors?  ", 
                attribute:"", 
                op1:"None",  
                op2:"Vector multiplication 1", 
                op3:"Vector multiplication -1", 
                op4:"Vector multiplication 0", 
                proof:"θ = 0 or, If π,  sin θ = 0 \n\n Therefore, a × b = 0 means, when the vector is parallel, their vector multiplication is zero.", 
                pic: "", 
                picon: false ,
                picproof: "",},

              "l1c302q16":{},
