"l1c303q1": {
	rightno: option2,
		question: "For the second quadrant point (-x, y), θ = ?",
			attribute: "0 ≤ θ ≤ 2π or -π < θ ≤ π",
				op1: "θ = tan⁻¹ y/-x = π/2 - tan⁻¹ y/x",
					op2: "θ = tan⁻¹ y/-x = π - tan⁻¹ y/x",
						op3: "θ = tan⁻¹ -y/x = π - tan⁻¹ y/-x",
							op4: "θ = tan⁻¹ y/-x = π + tan⁻¹ y/x",
								proof: "N/A",
									pic: "",
										picon: false,
											picproof: "",},
"l1c303q2": {
	rightno: option1,
		question: "For the third quadrant point (-x, -y), θ = ?",
			attribute: "0 ≤ θ < 2π",
				op1: "θ = tan⁻¹ -y/-x = π + tan⁻¹ y/x ",
					op2: "θ = tan⁻¹ -y/-x = π - tan⁻¹ y/x ",
						op3: "θ = tan⁻¹ y/x = π + tan⁻¹ -y/-x ",
							op4: "θ =  tan⁻¹ -y/-x = π + tan y/x ",
								proof: "N/A",
									pic: "",
										picon: false,
											picproof: "",},
"l1c303q3": {
	rightno: option4,
		question: "For the point (x, -y) of the fourth quadrant, θ = ?",
			attribute: "0 ≤ θ < 2π",
				op1: "θ = tan⁻¹ -y/x = π - tan⁻¹ y/x",
					op2: "θ = tan⁻¹ -y/x = 2π + tan⁻¹ y/x",
						op3: "θ = tan⁻¹ -y/x = 2π - tan⁻¹ -y/x",
							op4: "θ = tan⁻¹ -y/x = 2π - tan⁻¹ y/x",
								proof: "N/A",
									pic: "",
										picon: false,
											picproof: "",},
"l1c303q4": {
	rightno: option1,
		question: "For the fourth quadrant (x, -y), θ = ? ",
			attribute: "-π < θ ≤ π ",
				op1: "θ = tan⁻¹ -y/x = - tan⁻¹ y/x ",
					op2: "θ = tan⁻¹ -y/x = tan⁻¹ y/x ",
						op3: "θ = tan⁻¹ -y/x = tan⁻¹ -y/x",
							op4: "θ = tan⁻¹ -y/x = - tan⁻¹-y/x",
								proof: "N/A",
									pic: "",
										picon: false,
											picproof: "",},
"l1c303q5": {
	rightno: option3,
		question: "The distance between the point (0, 0) and the point (x, y), r = ?",
			attribute: "",
				op1: "r = √(y² - x²)",
					op2: "r = √(x² - y²)",
						op3: "r = √(x² + y²)",
							op4: "r = √(x + y)",
								proof: "\n\n cos θ = Vector / radius vector of point P = x/r \n\n So, x = r cos θ......(i) \n\n And, sin θ = Crore / radius vector of point P = y/r \n\n So, y = r sin θ......(ii) \n\n Squaring (i) and (ii) we get,  \n\n x² + y² = r² (cos θ)² + r² (sin θ)² \n\n = r²(cos²θ + sin² θ) = r². 1 =  r² \n\n Thereby, r =  √(x² + y²)",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q5.png'),},
"l1c303q6": {
	rightno: option4,
		question: "If the polar coordinates of two points (r₁, θ₁) and (r₂, θ₂) then the distance between them = ?",
			attribute: "A (r₁, θ₁), B (r₂, θ₂), AB = distance between A and B ",
				op1: "AB = r₁² + r₂² - 2r₁r₂ cos (θ₁ - θ₂)",
					op2: "AB = √{r₁² - r₂² + 2r₁r₂ cos (θ₁ - θ₂)}",
						op3: "AB = √{r₁² - r₂²  - 2r₁r₂ sin (θ₁ - θ₂)}",
							op4: "AB = √{r₁² + r₂² - 2r₁r₂ cos (θ₁ - θ₂)} ",
								proof: "\n\n The Cartesian coordinates of the points A (r₁, θ₁) and B (r₂, θ₂) are respectively A (r₁ cosθ₁, r₁ sinθ₁) and B (r₂ cosθ₂, r₂ sinθ₂). \n\n So, AB = √{(r₁ cosθ₁ - r₂ cosθ₂)² + (r₁ sinθ₁ - r₂ sinθ₂)²} \n\n =√{r₁² (cos²θ₁ + sin²θ₁) + r₂² (cos²θ₂ + sin²θ₂) - 2r₁r₂r₁ (cosθ₁ cosθ₂ + sinθ₁ sinθ₂)}  \n\n =  √{r₁² + r₂² - 2r₁r₂ cos (θ₁ - θ₂)}",
									pic: "",
										picon: false,
											picproof: "",},
"l1c303q7": {
	rightno: option1,
		question: "The coordinates of the dividing point in the ratio m₁: m₂, (x, y) = ?",
			attribute: "(x₁, y₁), (x₂, y₂) are two points and dividing these connecting lines in the ratio m₁: m₂, the line = (x, y)",
				op1: "(x, y) =  (m₁x₂ + m₂x₁ / m₁ + m₂, m₁y₂ + m₂y₁ / m₁ + m₂)",
					op2: "(x, y) = (m₁x₁ + m₂x₂ / m₁ + m₂, m₁y₁ + m₂y₂ / m₁ + m₂)",
						op3: "(x, y) = (m₁x₂ - m₂x₁ / m₁ + m₂, m₁y₂ - m₂y₁ / m₁ + m₂)",
							op4: "(x, y) = (m₁x₂ + m₂x₁ / m₁ - m₂, m₁y₂ + m₂y₁ / m₁ - m₂)",
								proof: "\n\n Here, OP = x₁,  AP = y₁ \n\n OQ = x₂, BQ = y₂ \n\n OR = x,  CR = y \n\n Now, \n\n As ꕔACS and ꕔBCT are similar,\n\n AS/CT = CS/BT = AC/CB = m₁/m₂...... (i) \n\n Again, AS = PR = OR - OP = x - x₁ \n\n And,  CT = RQ = OQ - OR = x₂ - x  \n\n So from (i), AS/CT = m₁/m₂ \n\n Or, x - x₁/ x₂ - x = m₁/m₂ \n\n or, m₂x - m₂x₁ = m₁x₂ - m₁x \n\n or, (m₁ + m₂) x = m₁x₂ + m₂x₁ \n\n So, x = m₁x₂ + m₂x₁ / m₁ + m₂ \n\n Also, CS = CR - RS = CR - PA = y - y₁ [ RS = PA] \n\n And, BT = QB - QT = QB - CR = y₂ - y [QT = CR] \n\n So, from (i) we get, CS/BT = m₁/m₂ \n\n or, y - y₁ / y₂ - y = m₁/m₂ \n\n Or, m₂y - m₂y₁ = m₁y₂ - m₁y \n\n Or, (m₁ + m₂) y = m₁y₂ + m₂y₁ \n\n So, y = m₁y₂ + m₂y₁ / m₁ + m₂ \n\n Thereby (x, y) =  (m₁x₂ + m₂x₁ / m₁ + m₂, m₁y₂ + m₂y₁ / m₁ + m₂)",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q7.png'),},

"l1c303q8": {
	rightno: option3,
		question: "The coordinates of the point of separation in the ratio m₁: m₂, (x, y) = ?",
			attribute: ": (x₁, y₁), (x₂, y₂) are two points and externally dividing these connecting lines in the ratio m₁: m₂, the line = (x, y)",
				op1: "(x, y) = (m₁x₂ + m₂x₁ / m₁ - m₂, m₁y₂ + m₂y₁ / m₁ - m₂)",
					op2: "(x, y) = (m₁x₂ + m₂x₁ / m₁ + m₂, m₁y₂ + m₂y₁ / m₁ + m₂)",
						op3: "(x, y) = (m₁x₂ - m₂x₁ / m₁ - m₂, m₁y₂ - m₂y₁ / m₁ - m₂)",
							op4: "(x, y) = (m₁x₂ - m₂x₁ / m₁ + m₂, m₁y₂ - m₂y₁ / m₁ + m₂)",
								proof: "\n\n PR : QR = m₁ / m₂ \n\n or, PR / QR = m₁ / m₂ \n\n Here, ꕔPRS and ꕔQRT are similar  \n\n So, PS / QT = RS / RT = PR / QR = m₁ / m₂......(i) \n\n From (i), PS / QT =  m₁ / m₂ \n\n or, x - x₁ / x - x₂ = m₁ / m₂  \n\n or, m₁x - m₁x₂ = m₂x - m₂x₁ \n\n Or, (m₁ - m₂)x = m₁x₂ - m₂x₁ \n\n So, x = m₁x₂ - m₂x₁ / m₁ - m₂ \n\n Again from (i), RS / RT = m₁ / m₂ \n\n or, y - y₁ / y - y₂ = m₁ / m₂ \n\n or, m₁y - m₁y₂ = m₂y - m₂y₁ \n\n or, (m₁ - m₂) y = m₁y₂ - m₂y₁ \n\n  So, y = m₁y₂ - m₂y₁ / m₁ - m₂ \n\n So, (x, y) = (m₁x₂ - m₂x₁ / m₁ - m₂, m₁y₂ - m₂y₁ / m₁ - m₂)",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q8.png'),},

"l1c303q9": {
	rightno: option4,
		question: "If (x₁, y₁) (x₂, y₂), (x₃, y₃) are the coordinates of the center of gravity of a triangle formed by a dot, then (x, y) = ?",
			attribute: "",
				op1: "(x, y) = ( x₁² + x₂² + x₃² / 9,  y₁² + y₂² + y₃² / 9 )",
					op2: "(x, y) = ( x₁ - x₂ - x₃ / 3,  y₁ - y₂ - y₃ / 3 )",
						op3: "(x, y) = ( x₁ + x₂ + x / 3,  y₁ + y₂ + y / 3 )",
							op4: "(x, y) = ( x₁ + x₂ + x₃ / 3,  y₁ + y₂ + y₃ / 3 ) ",
								proof: "\n\n Here, coordinate D of the midpoint of BC is (x₂ + x₂ / 2, y₂ + y₃ / 2) \n\n Suppose, the coordinates of G (x, y) and the point G intersect the AD AD in the ratio 2: 1. \n\n Thereby, AG : GD = 2 : 1 \n\n Then, x = { 2 . (x₂ + x₃ / 2) + 1 . x₁ } / 2 + 1 \n\n = x₁ + x₂ + x₃ / 3  \n\n And, y = { 2 . (y₂ + y₃ / 2) + 1 . y₁ } / 2 + 1 \n\n = y₁ + y₂ + y₃ / 3 \n\n So, center of gravity (x, y) = ( x₁ + x₂ + x₃ / 3,  y₁ + y₂ + y₃ / 3 )",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q9.png'),},

"l1c303q10": {
	rightno: option1,
		question: "If there is a point (x₁, y₁) above a straight line going to the origin, then m = ?",
			attribute: "",
				op1: "m = y₁ / x₁",
					op2: "m = y - y₁ / x - x₁",
						op3: "m =  y / x",
							op4: "m = - y₁ / x₁",
								proof: "N/A",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q11": {
	rightno: option2,
		question: "Equation of straight line parallel to x axis, y = ?",
			attribute: "",
				op1: "y = 1",
					op2: "y = b",
						op3: "y = a",
							op4: "y = 0",
								proof: "\n\n Since parallel to the x axis, y = b.  If said, the equation of the x axis or b = 0, then y = 0.",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q12": {
	rightno: option4,
		question: "Equation of a straight line parallel to the y axis, x = ?",
			attribute: "",
				op1: "x = 0",
					op2: "x = 1",
						op3: "x = a",
							op4: "x = a",
								proof: "\n\n Since parallel to the y axis, x = a.  If we say, the equation of the x axis or a = 0, then y = 0.",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q13": {
	rightno: option1,
		question: "Equation of the straight line to the origin, y = ?",
			attribute: "",
				op1: "y = mx",
					op2: "y = mx + c",
						op3: "y = 0",
							op4: "y = b",
								proof: "\n\n Since the origin is (0, 0) tanθ = y / x \n\n or, m = y / x... ..  [m = tanθ] \n\n or, y = mx",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q14": {
	rightno: option3,
		question: "Equation of the straight line of a given point, y = ?",
			attribute: "",
				op1: "y = b",
					op2: "y = mx ",
						op3: "y = mx + c",
							op4: "y = 0",
								proof: "",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q15": {
	rightno: option2,
		question: "Which of the following is the equation of a straight line passing through two points (not parallel to any axis)?",
			attribute: "",
				op1: "m = y / x",
					op2: "x - x₁ / x₁ - x ₂ = y - y₁ / y₁ - y₂",
						op3: "y =  (y₁ / x₁) m",
							op4: "x/a  + y/b = 1",
								proof: "\n\n Suppose the coordinates of two points (x₁, y₁) and x₂, y₂) \n\n Here, x₂ ≠ x₁ and y₂ ≠ y₁ \n\n Slope m and (x₁, y₁) equations of perpendicular bisectors, y - y₁ = m (x - x₁) ... ... (ii) \n\n Since, line (ii) passes through (x₂, y₂), \n\n Therefore, y₂ - y₁ = m (x₂ - x₁) \n\n So, m = y₂ - y₁ / x₂ - x₁ ... ... (iii) \n\n (ii) Replace the value of m in Equation No., \n\n y - y₁ = (y₂ - y₁ / x₂ - x₁) (x - x₁) ...... (iv) \n\n Or, y - y₁ / y₂ - y₁ = x - x₁ / x₂ - x₁ \n\n So, \n\n x - x₁ / x₁ - x ₂ = y - y₁ / y₁ - y₂",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q15.png'),},

"l1c303q16": {
	rightno: option3,
		question: "Which is the equation of the straight line intersected by both the axes?",
			attribute: "",
				op1: "x/a + y/b = - 1",
					op2: "x/a + y/b = 0",
						op3: "x/a + y/b = 1",
							op4: "x/a - y/b = -1",
								proof: "\n\n Suppose P (x, y) is any one element of a set of points located on a straight line AB.  Now draw the  \n\n perpendiculars PM and PN on the x axis and y axis from the point P and add O, P. \n\n ꕔOAB = ꕔOAP + ꕔOBP \n\n so, 1/2 OA.OB = 1/2 OA.PM + 1/2 OB.PN \n\n or, 1/2 a.b = 1/2 a.y + 1/2 b.x  \n\n Divide both sides by 1/2 ab, 1 = y / b + x / a \n\n So, x / a + y / b = 1 \n\n Option: Equation of straight line passing through the points A (a, 0) on the x axis and B (0, b) on the y axis, \n\n x - a / a - 0 = y - 0 / 0 - b  \n\n or, - bx + ab = ay  \n\n Or, bx + ay = ab \n\n So, x/a + y/b = 1",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q16.png'),},

"l1c303q17": {
	rightno: option1,
		question: "Determining a straight line equation :",
			attribute: "Which generates that angle along the positive side of the x axis and goes through a certain point.",
				op1: "x - x₁ / cosθ = y - y₁ / sinθ = r",
					op2: "x₁ - y₁ / x - y = rtanθ",
						op3: "x - x₁ / y - y₁  = rtanθ",
							op4: "x + x₁ / cosθ = y + y₁ / sinθ = r",
								proof: "\n\n Suppose a straight line LM generates an angle with the x axis. \n\n So, \u2220 MLX = \u2220 PQT = \n\n But, QT = SR = OR - OS = x - x7 \n\n PT = PR - TR = PR - QS = y - y₁ \n\n And PQ = r \n\n Now, let's get a right PQT triangle, \n\n QT / PQ = cosθ \n\n  QT = PQ cosθ \n\n So, x - x₁ = rcosθ \n\n Again, PT / PQ = sinθ \n\n PT = PQ sinθ \n\n  So, y - y₁ = r sinθ \n\n Thereby, \n\n x - x₁ / cosθ = y - y₁ / sinθ = r",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q18": {
	rightno: option4,
		question: "Angle between two asymmetrical lines, tanθ = ?",
			attribute: "",
				op1: "tanθ =  ax / by",
					op2: "tanθ = ± 1 + m₁m₂ / m₁ - m₂",
						op3: "tanθ = y / x",
							op4: "tanθ = ± m₁ - m₂ / 1 + m₁m₂",
								proof: "\n\n Suppose the inclined angles of the two straight lines AB and AC are 6;  So, ∠BAC =. \n\n Suppose ∠ABX = θ₁ and ∠ACX = θ₂ and θ₁> \n\n So, θ = θ₁ - θ₂ .. (i) \n\n Equation of two straight lines AB and AC, y = m₁x + c₁ \n\n And, y = m₂x + c₂ \n\n So, tanθ₁ = m₁ and tanθ₂ = m₂ \n\n  (i) From pie, tanθ = tan (θ₁ - θ₂) = tan θ₁ - tanθ₂ / 1 + tanθ₁ tanθ₂ \n\n That is, tanθ = m₁ - m₂ / 1 + m₁m₂ \n\n If θ₂>,, θ = θ₂ - θ₁ = - (θ₁ - θ₂) \n\n So, tanθ = tan {- (θ₁ - θ₂)} = - tan (θ₁ - θ₂) = - tanθ₁ - tanθ₂ / 1 + tanθ₁ tanθ₂ = - m₁ - m₂ / 1 + m₁m₂ \n\n So, tanθ = ± m₁ - m₂ / 1 + m₁m₂",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q19": {
	rightno: option3,
		question: "Which of the following is correct if two straight lines with m₁ and m₂ slopes are parallel to each other?",
			attribute: "",
				op1: "m₁ > m₂",
					op2: "m₁ ≠ m₂",
						op3: "m₁ = m₂",
							op4: "m₂ > m₁",
								proof: "N/A",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q20": {
	rightno: option4,
		question: "The condition that two straight lines are parallel to each other?",
			attribute: "The two lines are respectively: a₁x + b₁y + c₁ = 0 \n a₂x + b₂y + c₂ = 0",
				op1: "a₁ - b₁ = a₂ - b₂",
					op2: "a₁a₂ = b₁b₂",
						op3: "a₁ - a₂ = b₁ - b₂",
							op4: "a₁ / a₂ = b₁ / b₂",
								proof: "\n\n y = m₁x + c₁ \n\n And the condition that the two lines y = m₂x + c₂ parallel θ₁ = θ₂ \n\n tanθ₁ = tanθ₂ \n\n  or, m₁ = m₂ \n\n  Similarly, a₁x + b₁y + c₁ = 0 \n\n And a₂x + b₂y + c₂ = 0 The condition for the two lines to be parallel is - a₁ / b₁ = - a₂ / b₂ \n\n Or, a₁ / a₂ = b₁ / b₂",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q20.png'),},

"l1c303q21": {
	rightno: option3,
		question: "If m₁ and m₂ are two straight lines perpendicular to each other, m₁m₂ =?",
			attribute: "",
				op1: "m₁m₂ = ± 1",
					op2: "m₁m₂ = 1",
						op3: "m₁m₂ = -1",
							op4: "m₁m₂ = 0",
								proof: "\n\n The condition that two straight lines are perpendicular to each other is that their included angles are right angles i.e. θ₂ = θ₁ + 90 ° or θ₁ = θ₂ + 90 °, while (respectively) θ₂> θ₁ or θ₁>.  Now, m₂ = tanθ₂ = tan (θ₁ + 90 °) = - cotθ₁ = - 1 / m₁ \n\n Or, m₁ = tanθ₁ = tan (θ₂ + 90 °) = - cotθ₂ = - 1 / m₂. \n\n That is, m₁m₂ = - 1",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q22": {
	rightno: option1,
		question: "The condition for perpendicularity of two straight lines?",
			attribute: "",
				op1: "a₁a₂ + b₁b₂ = 0 ",
					op2: "a₁a₂ + b₁b₂ = 1",
						op3: "a₁a₂ + b₁b₂ = -1",
							op4: "a₁a₂ + b₁b₂ = -1/m",
								proof: "N/A",
									pic: "",
										picon: false,
											picproof: "",},

"l1c303q23": {
	rightno: option3,
		question: "What is the formula for the coordinate of the center of gravity of a triangle?",
			attribute: "",
				op1: "The coordinates of the center of gravity of a triangle = ( ( x¹+ x²+ x³)/2 ) , (y¹+ y²+ y³)/2) )",
					op2: "The coordinates of the center of gravity of a triangle = ( ( x¹+ x²+ x³)/1 ) , (y¹+ y²+ y³)/3) )",
						op3: "The coordinates of the center of gravity of a triangle = ( ( x¹+ x²+ x³)/3 ) , (y¹+ y²+ y³)/3) )",
							op4: "The coordinates of the center of gravity of a triangle = ( ( x¹+ x²+ x³)/2 ) , (y¹+ y²+ y³)/3) )",
								proof: "\n\n Suppose that the vertices of the triangle ABC are A (x₁, y₁), B (x₂, y₂) and C (x₃ y₃); The midpoints of the sides BC, CA and AB are D, E, F. Now if we draw the median AD, BE, CF, they will intersect at the point G. The point G is called the center of gravity of the triangle and it divides each median in the ratio 2: 1.  \n\n Now the coordinates of the midpoint D of BC is ((x₂ + x₃)/2   ,(y₂ + y₃)/2) \n\n Suppose, the coordinates of G (x, y), ∵ AG : GD = 2 : 1 \n\n ∴ x = 2 . (x₂ + x₃)/2 + 1 . (x₁)/(2 + 1) =  (x₁ + x₂ + x₃)/3 \n\n and, y = 2 . (y₂ + y₃)/2 + 1 . (y₁)/(2 + 1) = (y₁ + y₂ + y₃)/3 \n\n Thus, the center of gravity of ABC = ( ( x¹+ x²+ x³)/3 )   ,(y¹+ y²+ y³)/3)) \n\n Suppose that the vertices of the triangle ABC are A (x₁, y₁), B (x₂, y₂) and C (x₃ y₃); The midpoints of the sides BC, CA and AB are D, E, F. Now if we draw the median AD, BE, CF, they will intersect at the point G. The point G is called the center of gravity of the triangle and it divides each median in the ratio 2: 1. Now the coordinates of the midpoint D of BC is ((x₂ + x₃)/2   ,(y₂ + y₃)/2)",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q23.png'),},

"l1c303q24": {
	rightno: option1,
		question: "A(x₁, y₁), B(x₂, y₂) and C(x₃ , y₃) area of a triangle formed by the three points, ΔABC = ?",
			attribute: "",
				op1: "ΔABC  =1/2 \n{|x¹ y¹| + |x² y²|  + |x³ y³| \n |x² y²| + |x³ y³| + |x¹ y¹|}",
					op2: "ΔABC  =2 \n{|x¹ y¹| + |x² y²|  + |x³ y³| \n |x² y²| + |x³ y³| + |x¹ y¹|}",
						op3: "ΔABC  =\n{|x¹ y¹| + |x² y²|  + |x³ y³| \n |x² y²| + |x³ y³| + |x¹ y¹|}",
							op4: "ΔABC  =1/2 \n{|x² y²| + |x³ y³| + |x¹ y¹|\n |x¹ y¹| + |x² y²| + |x³ y³|}",
								proof: "\n\n Suppose the vertices of ΔABC are A(x₁, y₁), B (x₂, y₂), C (x₃, y₃). \n\n Draw perpendiculars AM, BL, CN from the points A, B, C on the x-axis respectively. Then, LM = OM - OL = x₃ - x₂ \n\n LM = OM - OL = x₁ - x₂ and MN = ON - OM \n\n = x₃ - x₁ \n\n ∴ Area of ΔABC = Area of Trapezium ABLM + Area of Trapezium AMNC - Area of Trapezium BLNC  \n\n = 1/2 (AM + BL) . LM + 1/2 (AM + CN) . MN - 1/2 (BL + CN) . LN \n\n = 1/2  {(y₁ + y₂) (x₁ - x₂) (y₁ + y₃) (x₃ - x₁) - (y₂ + y₃) (x₃ - x₂)} \n\n = 1/2  {x₁ (y₁ + y₂ - y₁ - y₃) + x₂ (y₂ + y₃ - y₁ - y₂) + x₃(y₁ + y₃ - y₂ - y₃)} \n\n ∴ Area of ΔABC = 1/2  {x₁(y₂ - y₃) + x₂ (y₃ - y₁) + x₃(y₁ - y₂)} \n\n ΔABC  =1/2 \n{|x¹ y¹| + |x² y²|  + |x³ y³| \n |x² y²| + |x³ y³| + |x¹ y¹|}",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q24.png'),},

"l1c303q25": {
	rightno: option4,
		question: "The connecting slope segment of the points (x₁ , y₁)  and (x₂ , y₂), m = ?",
			attribute: "",
				op1: "m = (y₁ - y₂)/(x₂  – x₁)",
					op2: "m = (x₁ - x₂)/(y₁ - y₂)",
						op3: "m = (y - y₂)/(x - x₂) × (y₁ - y₂)/(x₁ - x₂)",
							op4: "m = (y₁ - y₂)/(x₁ - x₂)",
								proof: "\n\n Suppose that the straight line AB passes through two fixed points P (x₁, y₁) and Q (x₂, y₂) and produces that angle along the positive side of the x-axis. Pull the PM ⊥ QN perpendicular to the x-axis from the points P and Q, respectively \n\n QR ⊥ PM and ∠QAN = Ø = \u2220 PQR      [ Similar angles] \n\n Now, PR = PM - RM = y₁ - y₂ and \n\n QR = NM = OM - ON = x₁ - x₂ \n\n ∴ The slope of the AB line, m = tan Ø = PR/QR = (y₁ - y₂)/(x₁ - x₂)",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q25.png'),},

"l1c303q26": {
	rightno: option1,
		question: "If, ax + by + c₁ = 0,  ax + by + c₂ = 0  then, d = ?",
			attribute: "d = The distance between two parallel lines",
				op1: "d = |(c₁ - c₂ )/( √(a² + b²)) |",
					op2: "d = |(c₂  – c₁ )/( √(a² + b²)) |",
						op3: "d = |( √(a² + b²)  )/(c₁ - c₂) |",
							op4: "d = |(c₁+ c₂ )/( √(a² + b²)) |",
								proof: "\n\n The given equations are: ax + by + c₁ = 0 ... (i)  \n\n   ax + by + c₂ = 0 ... (ii) \n\n The distance from the point 0 (0, 0) to the line (i) is ON = a . 0 + b . 0 + (c₁)/√(a² + b²) = (c₁)/√(a² + b²) \n\n ∴ The distance between two parallel lines, MN = ON - OM = d = | (c₁ - c₂ )/( √(a² + b²)) |",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q26.png'),},

"l1c303q27": {
	rightno: option2,
		question: "From (x₁, y₁) point to ax + by + c = 0 line, V = ?",
			attribute: "V = Vertical",
				op1: "V = | (ax + by + c)/√(a² + b²)  |",
					op2: "V = | (ax₁ + by₁ + c)/√(a² + b²)  |",
						op3: "V = | (ax₁ + by₁ + c)/√(a^2  - b²)  |",
							op4: "V = | (ax₁ + by₁ )/√(a² + b²)  |",
								proof: "\n\n The perpendicular distance of a straight line from a point is to determine the length of the perpendicular drawn on the straight line ax + by + c = 0 from the point P (x₁ y₁). Suppose the line ax + by + c = 0 intersects the axes x and y at points A and B respectively. The given equation can be written as follows: \n\n x/(-cla)  + y/clb = 1 = OA = - cla, and OB = - clb. \n\n ∴ AB² = OA² + OB² = c²/a² + c²/b²  \n\n ∴ AB = ± c/(ab√(a² + b²)) \n\n Draw the perpendiculars PM and PN on the x and y axis from the point P (x₁ y₁) respectively. Thus, PM = y₁, PN =  x₁ \n\n Suppose the perpendicular length drawn on the line P to AB is PR = d. \n\n Now, ΔOAB = ΔOAP + ΔOBP + ΔABP \n\n or,  1/2 (-c/a) (-c/b) =  1/2 (-c/a) . y₁ +  1/2 (-c/b) x₁ +  1/2  d × AB \n\n or, ± d × c/(ab√(a² + b²))  = (cx₁)/b + (cy₁)/a + c²/ab \n\n = ± d × √(a² + b²)  = ax₁ + by₁ + c, [multiply by ab/c ] \n\n or , d = ± ax₁ + by₁ + c/√(a² + b²)   \n\n ∴ The vertical length of the line ax + by + c = 0 from the point P (x₁ y₁), V = | (ax₁ + by₁ + c)/√(a² + b²)  |",
									pic: "",
										picon: false,
											picproof: require('../assets/l1c303q27.png'),},

"l1c303q28": { },
