//1st Paper
//Chapter 1

             "l1c301q1":{
                rightno: option1, 
                question: "Exchange rules for multiplication in case of matrix –", 
                attribute:"", 
                op1:"Not applicable",   
                op2:"Applicable", 
                op3:"One row will be larger than the other", 
                op4:"None", 
                proof:"N/A", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c301q2":{
                rightno: option4, 
                question: "What is determinants?", 
                attribute:"", 
                op1:"Unexceptional Matrix",  
                op2:"Number of matrix written in a particular form", 
                op3:"Coefficient", 
                op4:"Number of square matrix written in a particular form", 
                proof:"", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c301q3":{
                rightno: option2, 
                question: "What is the highest degree of determinant in both the quantity and coefficient of any of the n size determinants?", 
                attribute:"", 
                op1:"(n+1)",  
                op2:"(n – 1)", 
                op3:"(n – 1)²", 
                op4:"(1 – n)", 
                proof:"", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c301q4":{
                rightno: option3, 
                question: "As well as exchanging two rows or columns each other's space, the determinant found is the value of -  ", 
                attribute:"D = Determinants", 
                op1:"Negetive",  
                op2:"Positive", 
                op3:"Inverse marked number-index value ", 
                op4:"Marked number index value ", 
                proof:"\n\n The value of the new determinant found when two rows or columns exchange space in addition to one determinant will be equal to the number-index value of the given determinant but will be marked opposite. \n\n Means, If the value of the given determinant is D, the value of the new determinant will be -D     [D = Determinants] \n\n Suppose, Given determinants, \n\n |a₁ b₁ c₁ | \n |a₂ b₂ c₂ | \n |a₃ b₃ c₃ | \n = D \n\n and New Determinant, \n\n |b₁ a₁ c₁ | \n |b₂ a₂ c₂ | \n |b₃ a₃ c₃ | \n = D' \n\n Now, D = a₁(b₂c₃ – b₃c₂) - b₁(a₂c₃ – a₃c₂) + c₁(a₂b₃ – a₃b₂) \n\n - {b₁ (a₂ c₃-a₃ c₂ )-a₁ (b₂ c₃-b₃ c₂ )+ c₁ (a₃ b₂-a₂ b₃ )} \n\n = - D’ \n\n Therefore,  D’ = - D ", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c301q5":{
                rightno: option1, 
                question: "What will be the value of a determinant if two rows or columns are similar?", 
                attribute:"D = Determinants", 
                op1:"D = 0 ",  
                op2:"D = -1", 
                op3:"D = 1", 
                op4:"D = ∞", 
                proof:"\n\n Here \n\n |a₁ a₁ b₁ | \n |a₂ a₂ b₂ | \n |a₃ a₃ b₃ | \n = D = 0 [ Two columns are similar ] \n\n Suppose, The 1st and 2nd columns have been exchanged along with the given determinants. \n\n So that,\n\n |a₁ a₁ b₁ | \n |a₂ a₂ b₂ | \n |a₃ a₃ b₃ | \n = -D \n\n Turns out the two determinants are the same. \n\n So, D = - D \n\n or, 2D= 0 \n\n Means, D = 0	", 
                pic: "", 
                picon: false ,
                picproof: "",},
              "l1c301q6":{
                rightno: option2, 
                question: "Inverse Matrix, A⁻¹ = ?", 
                attribute:"A = Square Matrix, |A| = Determinants, Adj A = Adjoint Matrix, Aᵀ = Transpose Matrix, I = Unit Matrix", 
                op1:"A⁻¹ = |A|/(Adj A)",  
                op2:"A⁻¹ = (Adj A)/|A|  	[ |A|≠0 ]", 
                op3:"A⁻¹ = Aᵀ/I", 
                op4:"A⁻¹ = (Adj A)/|A| 	[ |A|= 0 ]", 
                proof:"\n\n In the case of any unexceptional matrix A, it can be proved that, \n\n A.(Adj A) = |A| . I , where I is Unit Matrix \n\n Or, A.(Adj A) = |A| . AA⁻¹		[ From the definition of inverse matrix] \n\n Therefore, A⁻¹ = (Adj A)/|A|  	[ |A|≠0 ]", 
                pic: "", 
                picon: false ,
                picproof: "",},

              "l1c301q7":{},
