//Chapter 9 - Differntiation

//Template
"l1c309qX":{
    rightno: option3,
    question: "",  
    attribute:"", 
    op1:"",  
    op2:"", 
    op3:"", 
    op4:"", 
    proof:"\n\n ",
    pic: "",         
    picon: false ,
    picproof: require('../assets/Picturename.png'), },

"l1c309qX":{
    rightno: option3,
    question: "",  
    attribute:"", 
    op1:"",  
    op2:"", 
    op3:"", 
    op4:"", 
    proof:"\n\n ",
    pic: "",         
    picon: false ,
    picproof: "",},

    
    //Starts here///////

"l1c309q1":{
    rightno: option4,
    question: "Formula of differentiation: d/dx (u ± v) = ?",  
    attribute:"", 
    op1:"d/dx (u ± v) = d/dx (u) - d/dx (v)",  
    op2:"d/dx (u ± v) = d/dx (u) + d/dx (v)", 
    op3:"d/dx (u ± v) = v d/dx(u) ± u d/dx(v)", 
    op4:"d/dx (u ± v) = d/dx (u) ± d/dx (v)", 
    proof:"\n\n Suppose, both u and y are functions of x. \n Suppose, y = u ± v, ... (i) then the function of y, x. \n Suppose a very slight increase in x, a similar increase in y, u, v to Δx, Δy, Δu, Δv, respectively, which are small enough. \n From ∴ y = u ± v, we get, y + Δy = (u + Δu) (v + Δv) ... (ii) \n By subtracting (ii) from (i), Δy = Δu ± Δv \n ∴ Δy/Δx = Δu/Δx ± Δv/Δx    [Divides both sides by Δx] \n Thus, lim┬(x→0)⁡(Δy/Δx) = (lim⁡ )┬(x→0)⁡(Δy/Δx) = (lim⁡)┬(x→0)⁡(Δv/Δx) \n ∴ dy/dx = du/dx ± dv/dx \n So, \n  d/dx (u ± v) = d/dx (u) ±  d/dx (v)",
    pic: "",         
    picon: false ,
    picproof: "",},


"l1c309q2":{
    rightno: option1,
    question: "Formula of differentiation: d/dx (uv) = ?",  
    attribute:"", 
    op1:"d/dx (uv)  = v d/dx(u) + u d/dx(v)",  
    op2:"d/dx (uv)  = d/dx (u) + d/dx (v)", 
    op3:"d/dx (uv)  = v d/dx(u) - u d/dx(v)", 
    op4:"d/dx (uv)  = u d/dx(v) - v d/dx(u)", 
    proof:"\n\n Suppose, y = uv ... (i), where both a and y are functions of x. So, \n y will be the function of x. Now a very small increase of x for Δx will be a corresponding increase for y, u, v , respectively Δy, Δu, Δv. \n ∴ y + Δy = (u + Δu) (v + Δv)	 [∵ supposed, y = u v] \n = u v + u. Δv + v. Δu + (Δu) (Δv) ... (ii) \n Subtracting from (ii) to (i) we get, \n Δy = u. Δv + v . Δu + (Δu) (Δv) \n ∴ Δy/Δx = u. Δv/Δx + v. Δu/Δx + Δu. Δv/Δx \n ∴ lim₍Δₓ→₀₎ (Δy/Δx) = lim₍Δₓ→₀₎  (u.Δv/Δx) + lim₍Δₓ→₀₎ (v.Δu/Δx) + lim₍Δₓ→₀₎ (Δu.Δv/Δx) [From the formula of limit] \n = u. lim₍Δₓ→₀₎ (Δv/Δx) + v. lim₍Δₓ→₀₎  (Δu/Δx  ) + lim₍Δₓ→₀₎ (Δu) × lim₍Δₓ→₀₎  (Δv/Δx)   … ….(iii) \n Since, Δx→ 0 then, Δu → 0; ∴ 〖lim〗_(Δx→0) Δu = 0 \n That is, lim₍Δₓ→₀₎ (Δu) × lim₍Δₓ→₀₎ (Δv/Δx) = 0 \n Thus, (iii) as defined \n d/dx (y) = u dv/dx + v du/dx + 0 \n ∴ d/dx (uv) = v d/dx(u) + u d/dx(v)",
    pic: "",         
    picon: false ,
    picproof: "",},


"l1c309q3":{
    rightno: option2,
    question: "Formula of differentiation: d/dx (u/v) =  (v.du/dx  - u.dv/dx)/v²",  
    attribute:"", 
    op1:"d/dx (u/v) = (v.du/dx  + u.dv/dx)/v² ",  
    op2:" d/dx (u/v) =  (v.du/dx  - u.dv/dx)/v²	", 
    op3:"d/dx (u/v) = v d/dx(u) × u d/dx(v)", 
    op4:"d/dx (u/v) = (v.du/dx  + u.dv/dx)/u² ", 
    proof:"\n\n Suppose, y = u/v ... (i), where both u and y have the function of x. So, \n  y will be the function of x. Suppose a very slight increase in x for Δx, a corresponding increase in y, u, v is Δy, Δu, Δv respectively. \n ∴ y + Δy = (u + Δu)/(v + Δv)   ... (ii) \n  Subtracting from (ii) to (i) we get, \n Δy = (u+Δu)/(v+Δv) - u/v = (vΔu - uΔy)/(v(v+Δv)) \n ∴ Δy/Δx =	(y.Δu/Δx  – u.Δv/Δx)/(v(v + Δv))		[Divides both sides by Δx] \n ∴ lim₍Δₓ→₀₎ (Δy/Δx) =  (lim₍Δₓ→₀₎  (Δu/Δx) - lim₍Δₓ→₀₎  (u.Δu/Δx))/(lim₍Δₓ→₀₎  {v (v+ Δv)})	[From the formula of limit] \n Now by definition, d/dx (y) = (v.du/dx  - u.dv/dx)/v²  		[Whereas, if Δx → 0, Δv → 0] \n So, \n  d/dx (u/v) = (v.du/dx  - u.dv/dx)/v²",
    pic: "",         
    picon: false ,
    picproof: "",},


"l1c309q4":{
    rightno: option4,
    question: "Which one is the correct formula of differentiation?",  
    attribute:"", 
    op1:"dz = f (x) dx",  
    op2:"dz = f′ (x)", 
    op3:"dz = f′ (z) dx", 
    op4:"dz = f′ (x) dx", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},


"l1c309q5":{
    rightno: option1,
    question: "lim {u(x) ± v(x) ± w(x)} = ?",  
    attribute:"u, v, w are the funtion of x", 
    op1:"lim {u(x) ± v(x) ± w(x)} = lim {u(x)} ± lim {v(x)} ± lim {w(x)}",  
    op2:"lim {u(x) ± v(x) ± w(x)} = lim {x(u)} ± lim {x(v)} ± lim {x(w)}", 
    op3:"lim {u(x) ± v(x) ± w(x)} = lim {x(u+v+w)}", 
    op4:"lim {u(x) ± v(x) ± w(x)} =lim {uvw(x)}", 
    proof: "\n\n A fundamental theorem of limits: the limit of the algebraic sum of two or more (finite number) functions is equal to the algebraic sum of the separate limits of each of them. So, \n  \n lim {u(x) ± v(x) ± w(x)} = lim {u(x)} ± lim {v(x)} ± lim {w(x)}",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q6":{
    rightno: option2,
    question: "lim {u(x) × v(x)} = ?",  
    attribute:"", 
    op1:"lim {u(x) × v(x)} = lim {v(x)} - lim {u(x)}",  
    op2:"lim {u(x) × v(x)} = lim {u(x)} × lim {v(x)}", 
    op3:"lim {u(x) × v(x)} = lim {uv(x)}", 
    op4:"lim {u(x) × v(x)} = lim {u(x)} / lim {v(x)}", 
    proof:"\n\n The limit of the multiplication of two functions is equal to the product of their separate limits. So, \n  \n lim {u(x) × v(x)} = lim {u(x)} × lim {v(x)}",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q7":{
    rightno: option3,
    question: "lim { u(x)/v(x) } = ?",  
    attribute:"", 
    op1:"lim { u(x)/v(x) } = lim {u(x)} ± lim {v(x)} ± lim {w(x)}",  
    op2:"lim { u(x)/v(x) } = lim (u/v)x", 
    op3:"lim { u(x)/v(x) } = lim {u(x)} / lim {v(x)}", 
    op4:"lim { u(x)/v(x) } = lim {v(x)} / lim {u(x)}", 
    proof:"\n\n The limit of the quotient of two functions is equal to the quotient of their limits, if the limit of the denominator is not zero. So, \n  \n lim { u(x)/v(x) } = lim {u(x)} / lim {v(x)}",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q8":{
    rightno: option2,
    question: "d/dx (xⁿ) = ?",  
    attribute:"", 
    op1:"d/dx (xⁿ) = nxⁿ⁺¹",  
    op2:"d/dx (xⁿ) = nxⁿ⁻¹", 
    op3:"d/dx (xⁿ) = nxⁿ⁻¹ / 2", 
    op4:"d/dx (xⁿ) = nxⁿ⁻¹ / n-1", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q9":{
    rightno: option4,
    question: "logₓa = ?",  
    attribute:"", 
    op1:"logₓa = lna / logₑx",  
    op2:"logₓa = logₑx / lna", 
    op3:"logₓa = logₐe lnx", 
    op4:"logₓa = logₑa / lnx", 
    proof:"logₓa = logₑa × logₓe = logₑa × (1 / logₑx)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q10":{
    rightno: option3,
    question: "logₐx = ?",  
    attribute:"", 
    op1:"logₐx = logₑa / lnx",  
    op2:"logₐx = logₑa lnx", 
    op3:"logₐx = logₐe lnx", 
    op4:"logₐx = logₐe logₐx", 
    proof:"logₐx = logₐe × logₑx = logₐe lnx",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q11":{
    rightno: option4,
    question: "Formula of differentiation: d/dx (sin⁻¹x) = ?        [-1 < x < 1]",  
    attribute:"", 
    op1:"d/dx (sin⁻¹x) = 1 / √(x²-1)",  
    op2:"d/dx (sin⁻¹x) = 1 / (1+x²)", 
    op3:"d/dx (sin⁻¹x) = √(1+x²)", 
    op4:"d/dx (sin⁻¹x) = 1 / √(1-x²)", 
    proof:"Suppose, y = sin⁻¹x. Then x = siny....(i) \n Differentiating by 1 on both sides in terms of y, we get,, \n dx/dy = cosy \n Thereby, dy/dx = 1/cosy   [dy/dx = 1/(dx/dy)] \n Means, d/dx(sin⁻¹x) = 1/cosy = 1 / √(1-sin²y) = 1 / √(1-x²) \n So, d/dx (sin⁻¹x) = 1 / √(1-x²)  [-1 < x < 1]",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q12":{
    rightno: option3,
    question: "Formula of differentiation: d/dx (cos⁻¹x) = ?",  
    attribute:"", 
    op1:"d/dx (cos⁻¹x) = √(1+x²)",  
    op2:"d/dx (cos⁻¹x) = 1 / (1+x²)", 
    op3:"d/dx (cos⁻¹x) = 1 / √(1-x²)", 
    op4:"d/dx (cos⁻¹x) = 1 / √(x²-1)", 
    proof:"Suppose, y = cos⁻¹x. Therefore, dx/dy = -siny = - √(1-cos²y) = - √(1-x²) \n Again, dy/dx = 1/(dx/dy) = - 1/√(1-x²) \n So, d/dx (cos⁻¹x) = d/dx (cos⁻¹x) = 1 / √(1-x²)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q13":{
    rightno: option2,
    question: "Formula of differentiation: d/dx (tan⁻¹x) = ?",  
    attribute:"", 
    op1:"d/dx (tan⁻¹x) = √(1+x²)",  
    op2:"d/dx (tan⁻¹x) = 1 / (1+x²)", 
    op3:"d/dx (tan⁻¹x) = 1 / √(x²-1)", 
    op4:"d/dx (tan⁻¹x) = 1 / √(1-x²)", 
    proof:"মনে করি, y = tan⁻¹x. Therefore, x = tany. \n Again, dx/dy (sec²y) = 1 + tan²y = 1 + x² \n or, dy/dx = 1/(dx/dy) = 1 / (1+x²) \n So, d/dx (tan⁻¹x) = 1 / (1+x²)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q14":{
    rightno: option2,
    question: "Formula of differentiation: d/dx ( cot⁻¹ 1-x / 1+x ) = ?",  
    attribute:"", 
    op1:"d/dx ( cot⁻¹ 1-x / 1+x ) = 1 / (1-x²)",  
    op2:"d/dx ( cot⁻¹ 1-x / 1+x ) = - 1 / (1+x²)", 
    op3:"d/dx ( cot⁻¹ 1-x / 1+x ) = - 1 / (1-x²)", 
    op4:"d/dx ( cot⁻¹ 1-x / 1+x ) = √(1+x²) / √(1-x²)", 
    proof:"Suppose, y = cot⁻¹ 1-x / 1+x = tan⁻¹ 1-x / 1+x = tan⁻¹ 1 - tan⁻¹ x = π/4 - tan⁻¹ x \n So, dy/dx = 0 - 1 / (1 + x²) = - 1 / (1 + x²)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q15":{
    rightno: option1,
    question: "Formula of differentiation: d/dx tan⁻¹ 1 / (√x² - 1) = ?",  
    attribute:"", 
    op1:"d/dx tan⁻¹ 1 / (√x² - 1) = - 1 / x√(x²-1)",  
    op2:"d/dx tan⁻¹ 1 / (√x² - 1) = 1 / x√(x²-1)", 
    op3:"d/dx tan⁻¹ 1 / (√x² - 1) = - 1 / (x²+1)", 
    op4:"d/dx tan⁻¹ 1 / (√x² - 1) = 1 / √(1-x²)", 
    proof:"Suppose, y = tan⁻¹ 1 / √x² - 1 = tan⁻¹ (1 / √sec²θ - 1)  [as, x = secθ] \n = tan⁻¹ 1/tanθ = tan⁻¹ cotθ = tan⁻¹ tan(π/2 - θ) = π/2 - sec⁻¹x \n So, d/dx tan⁻¹ 1 / (√x² - 1) = - 1 / x√(x²-1)",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q16":{
    rightno: option1,
    question: "Which of the following is Maclaurin's method?",  
    attribute:"", 
    op1:"f(x) = f(0) + xf'(0) + x²/2! fⁿ(0) + x³/3! fⁿ'(0)+...+ xⁿ/n! fⁿ(0) +...∞",  
    op2:"dz = f′ (x) dx", 
    op3:"Sₙ = 1/d ln [ (2a + (2n - 1) d) / (2a - d) ]", 
    op4:"Sₙ = a / (1 - r)", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q17":{
    rightno: option2,
    question: "Formula of differentiation: d/dx (cosx) = ?",  
    attribute:"", 
    op1:"d/dx (cosx) = sinx",  
    op2:"d/dx (cosx) = -sinx", 
    op3:"d/dx (cosx) = ", 
    op4:"d/dx (cosx) = ", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q18":{
    rightno: option3,
    question: "Formula of differentiation: d/dx (tanx) = ?",  
    attribute:"", 
    op1:"d/dx (tanx) = 1 / √(1-x²)",  
    op2:"d/dx (tanx) = - sec²x cot²x", 
    op3:"d/dx (tanx) = sec²x", 
    op4:"d/dx (tanx) = -sec²x", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q19":{
    rightno: option4,
    question: "Formula of differentiation: d/dx (cotx) = ?",  
    attribute:"", 
    op1:"d/dx (cotx) = -sec²x",  
    op2:"d/dx (cotx) = tanx cotx", 
    op3:"d/dx (cotx) = ln(cosec²x)", 
    op4:"d/dx (cotx) = -cosec²x", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q20":{
    rightno: option3,
    question: "Formula of differentiation: d/dx (secx) = ?",  
    attribute:"", 
    op1:"d/dx (secx) = - tanx",  
    op2:"d/dx (secx) = - sec²x tanx", 
    op3:"d/dx (secx) = secx tanx ", 
    op4:"d/dx (secx) = tanx", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q21":{
    rightno: option2,
    question: "Formula of differentiation: d/dx (cosecx) = ?",  
    attribute:"", 
    op1:"d/dx (cosecx) = - cosec²x cotx",  
    op2:"d/dx (cosecx) = - cosecx cotx", 
    op3:"d/dx (cosecx) = 1 / tan²x", 
    op4:"d/dx (cosecx) = -sinx", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q22":{
    rightno: option1,
    question: "Formula of differentiation: d/dx (ln x) = ?",  
    attribute:"", 
    op1:"d/dx (ln x) = 1/x",  
    op2:"d/dx (ln x) = 1", 
    op3:"d/dx (ln x) = x", 
    op4:"d/dx (ln x) = 0", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q23":{
    rightno: option4,
    question: "Formula of differentiation: d/dx (sinx) = ?",  
    attribute:"", 
    op1:"d/dx (sinx) = cosx",  
    op2:"d/dx (sinx) = -sinx", 
    op3:"d/dx (sinx) = -cosecx", 
    op4:"d/dx (sinx) = sec²x", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q24":{
    rightno: option3,
    question: "Formula of differentiation: d/dx (eˣ) = ?",  
    attribute:"", 
    op1:"d/dx (eˣ) = 1/x",  
    op2:"d/dx (eˣ) = lneˣ", 
    op3:"d/dx (eˣ) = eˣ", 
    op4:"d/dx (eˣ) = 1", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q25":{
    rightno: option2,
    question: "Formula of differentiation: d/dx (aˣ) = ?",  
    attribute:"", 
    op1:"d/dx (aˣ) =  x lna",  
    op2:"d/dx (aˣ) = aˣ lna", 
    op3:"d/dx (aˣ) = aˣ", 
    op4:"d/dx (aˣ) = 1", 
    proof:"",
    pic: "",         
    picon: false ,
    picproof: "",},

"l1c309q26":{},
